Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2019-11, with the labels that each got.

#1050 Replaced all the $order->get_status() comparisons with $order->has_status(...) because it's filterable
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-order-handler.php
  includes/class-wc-stripe-webhook-handler.php
Labels: PaymentIntents / SCA, [Status] Needs Review

#927 Avoid re-mounting card elements if already in DOM
  assets/js/stripe.js
  assets/js/stripe.min.js
  languages/woocommerce-gateway-stripe.pot
Labels: [Status] Ready to Merge

#1075 PI: Do not update an intent's customer after intent creation.
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-customer.php
  languages/woocommerce-gateway-stripe.pot
Labels: [Status] Ready to Merge

#1085 Declare WordPress 5.3 and WooCommerce 3.8 compatibility
  readme.txt
  woocommerce-gateway-stripe.php
Labels: [Status] Ready to Merge

#1087 Add a filter so the checkbox for updating the payment method used in all subscriptions can be checked by default
  includes/compat/class-wc-stripe-sepa-subs-compat.php
  includes/compat/class-wc-stripe-subs-compat.php
Labels: WooCommerce Subscriptions, [Status] Ready to Merge

#1088 Add filter so the payment method can be updated for all subscriptions, not only active ones
  includes/compat/class-wc-stripe-sepa-subs-compat.php
  includes/compat/class-wc-stripe-subs-compat.php
Labels: WooCommerce Subscriptions, [Status] Ready to Merge

#1089 Ensuring subscriptions are added to the cart during payment requests.
  includes/payment-methods/class-wc-stripe-payment-request.php
Labels: [Status] Ready to Merge
