Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2019-10, with the labels that each got.

#1023 Fixing `is_prepaid_card` to make it work with source objects.
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
Labels: [Status] Ready to Merge

#1022 Upgrading to API version 2019-09-09
  includes/class-wc-stripe-api.php
Labels: Priority: Low, [Status] Needs Review

#1012 Fix the style notice
  includes/admin/class-wc-stripe-admin-notices.php
Labels: Priority: High, [Status] Needs Review

#1016 Do not use empty string as source for payment intent
  includes/compat/class-wc-stripe-subs-compat.php
Labels: [Status] Ready to Merge

#1024 Add SetupIntents so the customer can confirm an SCA-protected payment even on a free order
  assets/js/stripe.js
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-helper.php
  includes/class-wc-stripe-webhook-handler.php
  includes/compat/class-wc-stripe-pre-orders-compat.php
  includes/compat/class-wc-stripe-subs-compat.php
Labels: [Status] Ready to Merge

#1014 Add a notice for SCA readiness
  includes/admin/class-wc-stripe-admin-notices.php
Labels: Priority: High, [Status] Ready to Merge

#1009 Fixing a deprecated call to `woocommerce_get_page_id`.
  includes/class-wc-stripe-intent-controller.php
Labels: Priority: Low, [Status] Ready to Merge

#1031 adding unique anchor for styling
  includes/admin/class-wc-stripe-admin-notices.php
Labels: [Status] Ready to Merge

#991 SCA Subscriptions: Reminder Emails
  includes/class-wc-gateway-stripe.php
  includes/compat/class-wc-stripe-email-failed-authentication.php
  includes/compat/class-wc-stripe-email-failed-preorder-authentication.php
  includes/compat/class-wc-stripe-email-failed-renewal-authentication.php
  includes/compat/class-wc-stripe-subs-compat.php
  templates/emails/failed-preorder-authentication.php
  templates/emails/failed-renewal-authentication.php
  templates/emails/plain/failed-preorder-authentication.php
  templates/emails/plain/failed-renewal-authentication.php
  tests/phpunit/test-wc-stripe-sub-renewal.php
  woocommerce-gateway-stripe.php
Labels: [Status] Ready to Merge

#996 SCA Subs: Prevent payment retries and check for authentication instead
  includes/compat/class-wc-stripe-email-failed-renewal-authentication.php
  includes/compat/class-wc-stripe-subs-compat.php
Labels: [Status] Ready to Merge

#1044 Fix error in test for initial intent
  includes/class-wc-gateway-stripe.php
Labels: [Status] Ready to Merge

#1039 Fix Pre-Order retries
  includes/compat/class-wc-stripe-pre-orders-compat.php
Labels: [Status] Ready to Merge

#1043 Remove some dead code related with Customer object creation
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-customer.php
Labels: [Status] Ready to Merge
