Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2019-06, with the labels that each got.

#878 Enqueue woocommerce_stripe script alongside wc_stripe_payment_request script
  assets/js/stripe.js
  includes/class-wc-gateway-stripe.php
  includes/payment-methods/class-wc-stripe-payment-request.php
Labels: PaymentIntents / SCA, [Status] Ready to Merge

#870 Make the capture / cancel-auth processes work even if the order is in a custom status
  includes/class-wc-stripe-order-handler.php
Labels: [Status] Ready to Merge

#887 Proceed with current request using new login session to ensure consistent nonce
  changelog.txt
  includes/class-wc-gateway-stripe.php
  readme.txt
Labels: [Status] Ready to Merge

#885 Zero decimal update
  changelog.txt
  includes/class-wc-stripe-helper.php
Labels: [Status] Needs Review

#893 Updating the link in the 3DS notice.
  includes/admin/class-wc-stripe-admin-notices.php
Labels: [Status] Ready to Merge

#890 Fix duplicate intent actions when webhooks are enabled.
  changelog.txt
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-order-handler.php
  readme.txt
Labels: [Status] Ready to Merge

#901 Fix - Changing an order status to "Cancelled" will no longer refund the payment.
  changelog.txt
  includes/class-wc-stripe-order-handler.php
  readme.txt
  woocommerce-gateway-stripe.php
Labels: [Status] Ready to Merge
