Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2019-05, with the labels that each got.

#846 PR: Remove Stripe Checkout (the legacy modal)
  assets/js/stripe-admin.js
  assets/js/stripe-admin.min.js
  assets/js/stripe.js
  assets/js/stripe.min.js
  docs/api/README.md
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/stripe-settings.php
  includes/class-wc-gateway-stripe.php
  includes/compat/class-wc-stripe-sepa-subs-compat.php
  includes/compat/class-wc-stripe-subs-compat.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  languages/woocommerce-gateway-stripe.pot
  readme.txt
  tests/e2e/lib/store-owner-flow.js
  tests/e2e/lib/wp-admin-wc-settings-checkout-stripe.js
  tests/manual/manual-tests.md
  tests/manual/stripe-checkout.md
  wordpress_org_assets/screenshot-5.png
Labels: [Status] Ready to Merge

#845 PR: Payment Request Buttons: Add Puerto Rico to allowable countries list
  changelog.txt
  includes/payment-methods/class-wc-stripe-payment-request.php
Labels: [Status] Ready to Merge

#854 Small copy and tweaks
  .github/CONTRIBUTING.md
  readme.txt
  woocommerce-gateway-stripe.php
Labels: [Status] Ready to Merge

#782 Manual tests update
  tests/manual/manual-tests.md
  tests/manual/stripe-alipay.md
  tests/manual/stripe-bancontact.md
  tests/manual/stripe-bitcoin.md
  tests/manual/stripe-cc-elements.md
  tests/manual/stripe-cc.md
  tests/manual/stripe-checkout.md
  tests/manual/stripe-giropay.md
  tests/manual/stripe-ideal.md
  tests/manual/stripe-p24.md
  tests/manual/stripe-sepa.md
  tests/manual/stripe-sofort.md
  tests/manual/stripe-with-subscriptions.md
Labels: [Status] Ready to Merge

#868 SCA: Add compatibility back to WooCommerce 2.6
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/class-wc-gateway-stripe.php
Labels: [Status] Needs Review

#864 SCA: UX improvements for PaymentIntent verifications
  includes/class-wc-stripe-intent-controller.php
  includes/class-wc-stripe-webhook-handler.php
Labels: [Status] Needs Review

#869 SCA/FIX: Prevent multiple error messages because of saved cards
  assets/js/stripe.js
Labels: [Pri] Low

#875 Move 3D Secure notice to notices class, replacing Stripe Checkout notice
  includes/admin/class-wc-stripe-admin-notices.php
  includes/class-wc-gateway-stripe.php
Labels: [Status] Ready to Merge

#867 SCA/4.2.0
  assets/css/stripe-styles.css
  assets/css/stripe-styles.scss
  assets/js/stripe-admin.js
  assets/js/stripe-admin.min.js
  assets/js/stripe.js
  assets/js/stripe.min.js
  changelog.txt
  docs/api/README.md
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/class-wc-stripe-admin-notices.php
  includes/admin/stripe-settings.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-helper.php
  includes/class-wc-stripe-intent-controller.php
  includes/class-wc-stripe-order-handler.php
  includes/class-wc-stripe-webhook-handler.php
  includes/compat/class-wc-stripe-sepa-subs-compat.php
  includes/compat/class-wc-stripe-subs-compat.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  languages/woocommerce-gateway-stripe.pot
  package-lock.json
  readme.txt
  tests/e2e/lib/store-owner-flow.js
  tests/e2e/lib/wp-admin-wc-settings-checkout-stripe.js
  tests/manual/manual-tests.md
  tests/manual/stripe-checkout.md
  tests/phpunit/test-wc-stripe.php
  woocommerce-gateway-stripe.php
  wordpress_org_assets/screenshot-5.png
Labels: [Status] Ready to Merge
