Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2019-04, with the labels that each got.

#826 SCA: Generate PaymentIntents within `process_payment`
  assets/css/stripe-styles.css
  assets/css/stripe-styles.scss
  assets/js/stripe.js
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-helper.php
  includes/class-wc-stripe-webhook-handler.php
Labels: PaymentIntents / SCA, [Status] Needs Review

#834 Update the Stripe's API version we support
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-api.php
Labels: PaymentIntents / SCA, [Status] Needs Review

#847 Bail if the site is HTTP and testing mode is disabled
  includes/class-wc-gateway-stripe.php
Labels: [Status] Needs Review

#836 SCA: Respect the "capture charge immediately" setting when using Payment Intents
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-order-handler.php
  includes/class-wc-stripe-webhook-handler.php
Labels: PaymentIntents / SCA, [Status] Needs Review

#837 Add warning notice for merchants that use the Modal checkout
  changelog.txt
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/class-wc-stripe-admin-notices.php
  package.json
  readme.txt
  woocommerce-gateway-stripe.php
Labels: [Status] Ready to Merge
