Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2020-10, with the labels that each got.

#1301 Add off session payment intent filter
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
Labels: [Status] Ready to Merge

#1312 Add apple association and uninstall files
  tasks/release.js
Labels: [Status] Ready to Merge

#1317 Remove hard requirement for customer phone numbers with Apple Pay
  assets/js/stripe-payment-request.js
  assets/js/stripe-payment-request.min.js
  changelog.txt
  includes/admin/stripe-settings.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: [Status] Needs Design, [Status] Ready to Merge

#1320 Perform Apple Pay domain verification on setup outside of settings screen
  includes/class-wc-stripe-apple-pay-registration.php
Labels: [Status] Ready to Merge

#1259 Add secret toggles
  assets/js/stripe-admin.js
  assets/js/stripe-admin.min.js
  languages/woocommerce-gateway-stripe.pot
Labels: [Status] Ready to Merge

#1323 Fix displaying errors for SEPA
  assets/js/stripe.js
  assets/js/stripe.min.js
  changelog.txt
Labels: [Status] Ready to Merge

#1326 Update version to 4.5.3
  changelog.txt
  languages/woocommerce-gateway-stripe.pot
  readme.txt
Labels: [Status] Needs Review

#1329 Tweak wording of Apple Pay Stripe Dashboard link
  includes/admin/stripe-settings.php
Labels: [Status] Ready to Merge

#1328 Apple Pay: Only report domain association file copy error if not already present
  includes/class-wc-stripe-apple-pay-registration.php
Labels: [Status] Ready to Merge

#1321 Fix the "Not a valid URL" notice
  includes/class-wc-stripe-apple-pay-registration.php
Labels: [Status] Ready to Merge

#1267 Migrate WCS Stripe Oauth code to Stripe
  assets/js/stripe-admin.js
  includes/abstracts/abstract-wc-stripe-connect-rest-controller.php
  includes/admin/stripe-settings.php
  includes/class-wc-gateway-stripe.php
  includes/connect/class-wc-stripe-connect-api.php
  includes/connect/class-wc-stripe-connect-rest-oauth-connect-controller.php
  includes/connect/class-wc-stripe-connect-rest-oauth-init-controller.php
  includes/connect/class-wc-stripe-connect.php
  woocommerce-gateway-stripe.php
Labels: [Status] Ready to Merge

#1345 Added security.md file
  SECURITY.md
  changelog.txt
  tasks/release.js
Labels: [Status] Ready to Merge
