Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2020-11, with the labels that each got.

#1343 Allow Alipay when store currency is set to CNY
  changelog.txt
  includes/admin/stripe-alipay-settings.php
  includes/admin/stripe-bancontact-settings.php
  includes/admin/stripe-eps-settings.php
  includes/admin/stripe-giropay-settings.php
  includes/admin/stripe-ideal-settings.php
  includes/admin/stripe-multibanco-settings.php
  includes/admin/stripe-p24-settings.php
  includes/admin/stripe-sepa-settings.php
  includes/admin/stripe-sofort-settings.php
  includes/payment-methods/class-wc-gateway-stripe-alipay.php
Labels: [Status] Ready to Merge

#1349 Add full name to stripe customer
  changelog.txt
  includes/class-wc-stripe-customer.php
Labels: [Status] Ready to Merge

#1310 Add site_url to all transactions, not just recurring
  changelog.txt
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
Labels: [Status] Ready to Merge

#1337 Add Inbox note for Apple Pay domain verification if needed
  includes/admin/class-wc-stripe-inbox-notes.php
  includes/class-wc-stripe-apple-pay-registration.php
  woocommerce-gateway-stripe.php
Labels: [Status] Ready to Merge

#1358 Update wp.org assets to new woo purple.
  wordpress_org_assets/banner-1544x500.png
  wordpress_org_assets/banner-772x250.png
  wordpress_org_assets/icon-128x128.png
  wordpress_org_assets/icon-256x256.png
Labels: [Status] Needs Review

#1357 Serve Apple Pay domain association file via rewrite rule
  includes/class-wc-stripe-apple-pay-registration.php
  woocommerce-gateway-stripe.php
Labels: [Status] Ready to Merge

#1365 Show Apple Pay holiday marketing note on setup success
  includes/admin/class-wc-stripe-inbox-notes.php
  includes/class-wc-stripe-apple-pay-registration.php
Labels: Apple Pay, [Status] Needs Review

#1367 Avoid Apple Pay payment failure on non-required phone field
  assets/js/stripe-payment-request.js
Labels: [Status] Ready to Merge

#1369 Provide defaults for missing settings on initial gateway settings save
  woocommerce-gateway-stripe.php
Labels: [Status] Ready to Merge

#1370 Roll for version 4.5.4
  assets/js/stripe-admin.min.js
  assets/js/stripe-payment-request.min.js
  changelog.txt
  composer.lock
  languages/woocommerce-gateway-stripe.pot
  package-lock.json
  package.json
  readme.txt
  woocommerce-gateway-stripe.php
Labels: [Status] Needs Review

#1372 Guard against fatal error on Inbox data store load
  changelog.txt
  includes/admin/class-wc-stripe-inbox-notes.php
Labels: [Status] Needs Review

#1377 Set max compression level for zip file produced by build:release.
  tasks/release.js
Labels: [Status] Ready to Merge
