Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2020-05, with the labels that each got.

#1166 Prevent exposing secret keys in the frontend
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/class-wc-stripe-admin-notices.php
  includes/admin/stripe-settings.php
  includes/class-wc-gateway-stripe.php
  includes/payment-methods/class-wc-stripe-payment-request.php
Labels: [Status] Ready to Merge

#1179 WordPress.org assets update
  readme.txt
  wordpress_org_assets/screenshot-1.png
  wordpress_org_assets/screenshot-2.png
  wordpress_org_assets/screenshot-3.png
  wordpress_org_assets/screenshot-4.png
Labels: [Status] Needs Review

#807 Added Missing $source_id, when creating Stripe Customer & Saving Token as $source
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
Labels: [Status] Needs Review

#1188 Add docker config and setup for local development
  .gitattributes
  .gitignore
  bin/docker-setup.sh
  default.env
  docker-compose.yml
  docker/dev-php.ini
  docker/wordpress_xdebug/Dockerfile
  docs/DOCKER.md
  package-lock.json
  package.json
  tests/README.md
  tests/bin/install.sh
Labels: Engineering, [Status] Ready to Merge

#1189 Remove support for WC versions before 3.0
  .travis.yml
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/class-wc-stripe-admin-notices.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-helper.php
  includes/class-wc-stripe-intent-controller.php
  includes/class-wc-stripe-logger.php
  includes/class-wc-stripe-order-handler.php
  includes/class-wc-stripe-sepa-payment-token.php
  includes/class-wc-stripe-webhook-handler.php
  includes/compat/class-wc-stripe-pre-orders-compat.php
  includes/compat/class-wc-stripe-sepa-subs-compat.php
  includes/compat/class-wc-stripe-subs-compat.php
  includes/payment-methods/class-wc-gateway-stripe-alipay.php
  includes/payment-methods/class-wc-gateway-stripe-bancontact.php
  includes/payment-methods/class-wc-gateway-stripe-eps.php
  includes/payment-methods/class-wc-gateway-stripe-giropay.php
  includes/payment-methods/class-wc-gateway-stripe-ideal.php
  includes/payment-methods/class-wc-gateway-stripe-multibanco.php
  includes/payment-methods/class-wc-gateway-stripe-p24.php
  includes/payment-methods/class-wc-gateway-stripe-sepa.php
  includes/payment-methods/class-wc-gateway-stripe-sofort.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  templates/emails/failed-preorder-authentication.php
  tests/phpunit/test-wc-stripe-level-3-data.php
  tests/phpunit/test-wc-stripe-payment-gateway.php
  tests/phpunit/test-wc-stripe-sub-initial.php
  tests/phpunit/test-wc-stripe-sub-renewal.php
  woocommerce-gateway-stripe.php
Labels: Engineering, [Status] Ready to Merge

#1185 Level 3 data: Cast shipping amounts to float when adding
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
Labels: [Status] Ready to Merge

#1197 Add support for custom payment request button
  assets/css/stripe-styles.css
  assets/css/stripe-styles.scss
  assets/js/stripe-admin.js
  assets/js/stripe-admin.min.js
  assets/js/stripe-payment-request.js
  assets/js/stripe-payment-request.min.js
  includes/admin/stripe-settings.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  languages/woocommerce-gateway-stripe.pot
Labels: [Status] Ready to Merge

#1204 Fix custom button class typo and rebuild files
  assets/js/stripe-payment-request.js
  assets/js/stripe-payment-request.min.js
  languages/woocommerce-gateway-stripe.pot
Labels: [Status] Ready to Merge, [Type] Bug

#1191 Update shipping methods request
  composer.json
  composer.lock
  includes/payment-methods/class-wc-stripe-payment-request.php
  phpcs.xml.dist
  tests/phpunit/test-wc-stripe-payment-request.php
Labels: [Status] Ready to Merge

#1183 Riaan knoetze 1182 compatibility update
  readme.txt
  woocommerce-gateway-stripe.php
Labels: [Status] Ready to Merge

#1192 Listen on mouseup for when a user click the up qty field buttons
  assets/js/stripe-payment-request.js
  assets/js/stripe-payment-request.min.js
Labels: [Status] Needs Author Reply

#1205 Allowing state abbreviations to be used in payment requests
  includes/payment-methods/class-wc-stripe-payment-request.php
Labels: [Status] Needs Review

#1202 Add Google Pay branded button
  assets/css/stripe-styles.css
  assets/css/stripe-styles.scss
  assets/js/stripe-admin.js
  assets/js/stripe-admin.min.js
  assets/js/stripe-payment-request.js
  assets/js/stripe-payment-request.min.js
  includes/admin/stripe-settings.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  languages/woocommerce-gateway-stripe.pot
Labels: [Status] Ready to Merge

#1210 #1208: Move links from action to meta section
  woocommerce-gateway-stripe.php
Labels: [Status] Needs Review

#1215 Display Apple Pay button with text based on branded_type
  assets/js/stripe-payment-request.js
  assets/js/stripe-payment-request.min.js
Labels: [Status] Ready to Merge
