Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2021-12, with the labels that each got.

#2212 Hide Enable separate credit card form when UPE is enabled
  client/settings/payments-and-transactions-section/index.js
Labels: pr: ready to merge, component: UPE settings

#2211 Add capture payment API endpoint
  changelog.txt
  includes/admin/class-wc-rest-stripe-orders-controller.php
  includes/class-wc-stripe-order-handler.php
  readme.txt
  tests/phpunit/admin/test-class-wc-rest-stripe-orders-controller.php
Labels: pr: ready to merge

#2221 Use node version from .nvmrc
  .github/workflows/js-tests.yml
  .github/workflows/linting.yml
Labels: pr: ready to merge

#2219 Reword "Stripe docs" to "Stripe plugin docs"
  client/settings/general-settings-section/disable-upe-confirmation-modal.js
  client/settings/payment-settings/index.js
Labels: pr: needs review

#2220 UPE feature flag design update
  changelog.txt
  client/data/settings/hooks.js
  client/index.js
  client/settings/advanced-settings-section/__tests__/index.test.js
  client/settings/advanced-settings-section/debug-mode.js
  client/settings/advanced-settings-section/experimental-features.js
  client/settings/advanced-settings-section/index.js
  client/settings/general-settings-section/__tests__/general-settings-section.test.js
  client/settings/general-settings-section/index.js
  client/settings/general-settings-section/upe-opt-in-banner.js
  client/settings/payment-gateway-manager/__tests__/index.test.js
  client/settings/payment-gateway-manager/index.js
  client/settings/payment-gateway-manager/opt-in-banner-image.js
  client/settings/payment-gateway-manager/opt-in-banner.js
  client/settings/upe-opt-in-banner/__tests__/upe-opt-in-banner.test.js
  client/settings/upe-opt-in-banner/index.js
  client/settings/upe-toggle/__tests__/provider.test.js
  client/settings/upe-toggle/provider.js
  client/upe-onboarding-wizard/__tests__/onboarding-wizard.test.js
  client/upe-onboarding-wizard/index.js
  client/upe-onboarding-wizard/onboarding-wizard.js
  client/upe-onboarding-wizard/style.scss
  client/upe-onboarding-wizard/upe-preview-methods-selector/__tests__/add-payment-methods-task.test.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/__tests__/enable-upe-preview-task.test.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/__tests__/setup-complete-task.test.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/add-payment-methods-task.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/enable-upe-preview-task.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/enable-upe-preview-task.scss
  client/upe-onboarding-wizard/upe-preview-methods-selector/payment-method-checkbox/__tests__/payment-method-checkbox.test.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/payment-method-checkbox/index.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/payment-method-checkbox/style.scss
  client/upe-onboarding-wizard/upe-preview-methods-selector/setup-complete-task.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/setup-complete-task.scss
  client/upe-onboarding-wizard/upe-preview-methods-selector/style.scss
  client/upe-onboarding-wizard/wizard/README.md
  client/upe-onboarding-wizard/wizard/collapsible-body.js
  client/upe-onboarding-wizard/wizard/collapsible-body.scss
  client/upe-onboarding-wizard/wizard/style.scss
  client/upe-onboarding-wizard/wizard/task-item.js
  client/upe-onboarding-wizard/wizard/task-item.scss
  client/upe-onboarding-wizard/wizard/task-list.js
  client/upe-onboarding-wizard/wizard/task/context.js
  client/upe-onboarding-wizard/wizard/task/index.js
  client/upe-onboarding-wizard/wizard/test/index.js
  client/upe-onboarding-wizard/wizard/wrapper/context.js
  client/upe-onboarding-wizard/wizard/wrapper/provider.js
  includes/admin/class-wc-rest-stripe-settings-controller.php
  includes/admin/class-wc-stripe-onboarding-controller.php
  includes/notes/class-wc-stripe-upe-availability-note.php
  readme.txt
  tests/phpunit/test-class-wc-stripe-upe-availability-note.php
  webpack.config.js
  woocommerce-gateway-stripe.php
Labels: pr: needs review, component: UPE settings

#2222 Fix secret key getter
  changelog.txt
  includes/class-wc-stripe-api.php
  readme.txt
Labels: component: stripe checkout

#2224 Ensure payment has captured before setting order's payment as complete
  includes/class-wc-stripe-webhook-handler.php
Labels: pr: needs review

#2213 Add webhook information to api key dialog
  changelog.txt
  client/components/webhook-information/__tests__/index.test.js
  client/components/webhook-information/index.js
  client/settings/account-details/index.js
  client/settings/connect-stripe-account/__tests__/connect-stripe-account.test.js
  client/settings/payment-gateway-section/index.js
  client/settings/payment-settings/__tests__/general-settings-section.test.js
  client/settings/payment-settings/account-keys-modal.js
  readme.txt
Labels: pr: ready to merge

#2215 Add additional tests for payment capture failure cases
  includes/admin/class-wc-rest-stripe-orders-controller.php
  tests/phpunit/admin/test-class-wc-rest-stripe-orders-controller.php
Labels: pr: ready to merge

#2230 Fix fragile payment gateway names
  includes/admin/class-wc-stripe-admin-notices.php
Labels: pr: needs review

#2236 Add 'listen' NPM script
  package.json
Labels: priority: low

#2226 Redirect to settings tab after account is connected
  changelog.txt
  client/settings/connect-stripe-account/index.js
  client/settings/payment-settings/account-keys-modal.js
  includes/connect/class-wc-stripe-connect.php
Labels: pr: ready to merge

#2237 Add conditional before trying to add mask to CPF/CNPJ field
  assets/js/stripe.js
  assets/js/stripe.min.js
  changelog.txt
Labels: pr: ready to merge

#2235 Show toast when payment methods list is updated
  changelog.txt
  client/data/account/__tests__/actions.test.js
  client/data/account/actions.js
  client/data/account/selectors.js
Labels: pr: ready to merge

#2216 fixed bug that would require customer to click on use new payment met…
  changelog.txt
  client/classic/upe/index.js
Labels: pr: ready to merge

#2243 Prompt message when navigating out Stripe settings with unsaved changes
  changelog.txt
  client/settings/save-settings-section/index.js
  client/settings/settings-manager/index.js
  client/utils/use-confirm-navigation.js
  readme.txt
Labels: pr: in progress

#2250 Add a reference to the transpiled JS file in POT file reference comments
  .gitignore
  babel.config.js
  bin/update-pot-file-references.php
  composer.json
  composer.lock
  languages/README.md
  languages/woocommerce-gateway-stripe.pot
  package.json
  tasks/release.js
  webpack.config.js
Labels: pr: needs review

#2245 Tweaks in the connect account modal
  changelog.txt
  client/data/account-keys/__tests__/actions.test.js
  client/data/account-keys/actions.js
  client/settings/payment-settings/account-keys-modal.js
  includes/admin/class-wc-rest-stripe-account-keys-controller.php
  tests/phpunit/test-wc-rest-stripe-account-keys-controller.php
Labels: pr: needs review

#2252 Fix ESLint warnings
  client/components/tooltip/tooltip-base.js
  client/utils/use-confirm-navigation.js
Labels: pr: in progress

#2248 Use the LoadingMask component from WooCommerce Blocks for PRB loading status in the Cart and Checkout Blocks
  changelog.txt
  client/blocks/payment-request/payment-request-express.js
  readme.txt
Labels: pr: ready to merge, type: technical debt, category: refactor, component: blocks
