Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2021-04, with the labels that each got.

#1498 Hide Payment Request Buttons when guest checkout is not possible
  changelog.txt
  includes/class-wc-stripe-apple-pay-registration.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: pr: needs review

#1508 Map WooCommerce states and Payment Request states
  changelog.txt
  includes/constants/class-wc-stripe-payment-request-button-states.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: pr: ready to merge

#1512 Pass customer language/locale to Stripe upon creation or modification.
  changelog.txt
  includes/class-wc-stripe-customer.php
  readme.txt
Labels: pr: needs author reply, pr: ready to merge

#1530 Payment Request: Fix non-default block checkout page and add support for product_page shortcode
  includes/payment-methods/class-wc-stripe-payment-request.php
Labels: pr: ready to merge

#1531 [WC_Stripe_Subs_Compat] Use `get_parent` method to get the subscription’s parent order
  changelog.txt
  includes/compat/class-wc-stripe-sepa-subs-compat.php
  includes/compat/class-wc-stripe-subs-compat.php
  readme.txt
Labels: pr: ready to merge

#1529 Return a WP_Error to indicate refund initiation problems
  changelog.txt
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  readme.txt
Labels: pr: ready to merge

#1507 Save regular and 3DS cards only after payment intent is confirmed
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-customer.php
  includes/class-wc-stripe-intent-controller.php
Labels: pr: needs author reply

#1543 Payment Request: Fix shipping calculation for UK and CA postal codes with Apple Pay
  changelog.txt
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: pr: ready to merge
