Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2021-08, with the labels that each got.

#1655 Update the GH workflows Ubuntu to 18.04 (from 16.04)
  .github/workflows/compatibility.yml
  .github/workflows/linting.yml
  .github/workflows/unit-testing.yml
Labels: pr: needs review

#1649 Spelling update CTA disconnected account
  includes/class-wc-gateway-stripe.php
Labels: pr: ready to merge

#1656 Return http 204 when webhook validation fails
  changelog.txt
  includes/class-wc-stripe-webhook-handler.php
Labels: component: webhooks, pr: ready to merge, priority: critical, type: bug

#1658 Fix possible issue with undefined variable: prepared_source
  changelog.txt
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/class-wc-stripe-order-handler.php
  includes/class-wc-stripe-webhook-handler.php
Labels: pr: ready to merge

#1657 Fix payments with custom order status made via payment or setup intents
  changelog.txt
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-webhook-handler.php
  includes/payment-methods/class-wc-gateway-stripe-alipay.php
  includes/payment-methods/class-wc-gateway-stripe-bancontact.php
  includes/payment-methods/class-wc-gateway-stripe-eps.php
  includes/payment-methods/class-wc-gateway-stripe-giropay.php
  includes/payment-methods/class-wc-gateway-stripe-ideal.php
  includes/payment-methods/class-wc-gateway-stripe-multibanco.php
  includes/payment-methods/class-wc-gateway-stripe-p24.php
  includes/payment-methods/class-wc-gateway-stripe-sepa.php
  includes/payment-methods/class-wc-gateway-stripe-sofort.php
Labels: pr: needs review

#1647 UPE: migrate the upe javascript to use the wp-scripts pipeline (webpack)
  client/api/index.js
  client/blocks/credit-card/index.js
  client/blocks/credit-card/payment-method.js
  client/blocks/credit-card/use-checkout-subscriptions.js
  client/blocks/credit-card/use-payment-processing.js
  client/blocks/payment-request/branded-buttons.js
  client/blocks/payment-request/custom-button.js
  client/blocks/payment-request/event-handlers.js
  client/blocks/payment-request/hooks.js
  client/blocks/payment-request/index.js
  client/blocks/payment-request/login-confirmation.js
  client/blocks/payment-request/payment-request-express.js
  client/classic/upe/index.js
  client/classic/upe/style.scss
  client/stripe-utils/constants.js
  client/stripe-utils/index.js
  client/stripe-utils/load-stripe.js
  client/stripe-utils/normalize.js
  client/stripe-utils/type-defs.js
  client/stripe-utils/utils.js
  client/styles/upe/index.js
  client/styles/upe/test/index.js
  client/styles/upe/test/utils.js
  client/styles/upe/upe-styles.js
  client/styles/upe/utils.js
  includes/class-wc-stripe-intent-controller.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-cc.php
  package-lock.json
  package.json
  webpack.config.js
Labels: pr: needs author reply, pr: ready to merge

#1675 deps: add nvmrc file
  .nvmrc
Labels: pr: ready to merge

#1674 Save payment method on 3DS flow, when requested, in Block-based checkout
  changelog.txt
  includes/admin/stripe-settings.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-blocks-support.php
Labels: pr: ready to merge

#1646 Add UPE
  assets/js/stripe-admin.js
  client/api/index.js
  client/blocks/credit-card/index.js
  client/blocks/credit-card/payment-method.js
  client/blocks/credit-card/use-checkout-subscriptions.js
  client/blocks/credit-card/use-payment-processing.js
  client/blocks/payment-request/branded-buttons.js
  client/blocks/payment-request/custom-button.js
  client/blocks/payment-request/event-handlers.js
  client/blocks/payment-request/hooks.js
  client/blocks/payment-request/index.js
  client/blocks/payment-request/login-confirmation.js
  client/blocks/payment-request/payment-request-express.js
  client/classic/upe/index.js
  client/classic/upe/style.scss
  client/stripe-utils/constants.js
  client/stripe-utils/index.js
  client/stripe-utils/load-stripe.js
  client/stripe-utils/normalize.js
  client/stripe-utils/type-defs.js
  client/stripe-utils/utils.js
  client/styles/upe/index.js
  client/styles/upe/test/index.js
  client/styles/upe/test/utils.js
  client/styles/upe/upe-styles.js
  client/styles/upe/utils.js
  includes/admin/stripe-settings.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-feature-flags.php
  includes/class-wc-stripe-intent-controller.php
  includes/payment-methods/class-wc-gateway-stripe-alipay.php
  includes/payment-methods/class-wc-gateway-stripe-bancontact.php
  includes/payment-methods/class-wc-gateway-stripe-eps.php
  includes/payment-methods/class-wc-gateway-stripe-giropay.php
  includes/payment-methods/class-wc-gateway-stripe-ideal.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-bancontact.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-cc.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-eps.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-giropay.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-ideal.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
  package-lock.json
  package.json
  phpunit.xml.dist
  tests/phpunit/test-wc-stripe.php
  webpack.config.js
  woocommerce-gateway-stripe.php
Labels: pr: needs review, size: large

#1672 Use the plugin settings to choose PRB locations instead of filters
  changelog.txt
  includes/admin/stripe-settings.php
  includes/class-wc-stripe-blocks-support.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#1697 deps: husky, yarnhook
  .husky/post-checkout
  .husky/post-merge
  .husky/post-rewrite
  package-lock.json
  package.json
Labels: pr: ready to merge

#1700 Fix PRB product page location option
  includes/payment-methods/class-wc-stripe-payment-request.php
Labels: pr: needs review

#1691 Add UPE feature flag controller
  includes/admin/class-wc-rest-upe-flag-toggle-controller.php
  tests/phpunit/test-wc-rest-upe-flag-toggle-controller.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review, component: UPE

#1701 chore: add jest tests
  .github/workflows/js-tests.yml
  .github/workflows/php-tests.yml
  .jshintrc
  babel.config.js
  client/__tests__/dummy-react-base-test.test.js
  client/styles/upe/__tests__/index.js
  client/styles/upe/__tests__/utils.js
  package-lock.json
  package.json
  tests/js/jest-file-mock.js
  tests/js/jest-global-setup.js
  tests/js/jest-setup.js
  tests/js/jest.config.js
  webpack.config.js
Labels: pr: needs review

#1713 refactor: add settings UI flag
  changelog.txt
  includes/admin/class-wc-stripe-settings-controller.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-feature-flags.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#1733 Fix UPE running on PHP 8.0
  includes/class-wc-stripe-intent-controller.php
Labels: pr: needs review

#1710 feat: add Stripe setttings base layout
  babel.config.js
  client/settings/card-body.js
  client/settings/general-settings-section/index.js
  client/settings/index.js
  client/settings/payment-request-section/index.js
  client/settings/save-settings-section/__tests__/save-settings-section.test.js
  client/settings/save-settings-section/index.js
  client/settings/settings-layout.js
  client/settings/settings-manager/index.js
  client/settings/settings-section/__tests__/settings-section.test.js
  client/settings/settings-section/index.js
  client/settings/styles.scss
  includes/admin/class-wc-stripe-settings-controller.php
  package-lock.json
  package.json
Labels: pr: ready to merge

#1722 feat: add express checkout settings
  client/payment-method-icons/apple-pay/icon.svg
  client/payment-method-icons/apple-pay/index.js
  client/payment-method-icons/google-pay/icon.svg
  client/payment-method-icons/google-pay/index.js
  client/payment-method-icons/styles/base-icon.js
  client/payment-method-icons/styles/icon-with-shell.js
  client/settings/payment-request-section/__tests__/index.test.js
  client/settings/payment-request-section/index.js
  client/settings/settings-manager/index.js
  includes/admin/class-wc-stripe-settings-controller.php
  package-lock.json
  package.json
Labels: pr: needs review

#1659 UPE: Port CC happy flow from WCPay
  client/api/index.js
  client/classic/upe/index.js
  includes/class-wc-stripe-intent-controller.php
  includes/class-wc-stripe-order-handler.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-cc.php
Labels: pr: needs review

#1741 Add order metadata to UPE Stripe transaction
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review, component: UPE

#1724 feat: add UPE flag context provider
  client/settings/index.js
  client/settings/upe-toggle/__tests__/provider.test.js
  client/settings/upe-toggle/context.js
  client/settings/upe-toggle/provider.js
  includes/admin/class-wc-stripe-settings-controller.php
  package-lock.json
  package.json
Labels: pr: needs review

#1754 Feature: Show UPE opt-in banner
  client/components/pill/index.js
  client/payment-method-icons/all-payment-methods/icon.svg
  client/payment-method-icons/all-payment-methods/index.js
  client/settings/payment-methods/index.js
  client/settings/upe-opt-in-banner/__tests__/upe-opt-in-banner.test.js
  client/settings/upe-opt-in-banner/index.js
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/payment-methods/class-wc-gateway-stripe-alipay.php
  includes/payment-methods/class-wc-gateway-stripe-bancontact.php
  includes/payment-methods/class-wc-gateway-stripe-eps.php
  includes/payment-methods/class-wc-gateway-stripe-giropay.php
  includes/payment-methods/class-wc-gateway-stripe-ideal.php
  includes/payment-methods/class-wc-gateway-stripe-multibanco.php
  includes/payment-methods/class-wc-gateway-stripe-p24.php
  includes/payment-methods/class-wc-gateway-stripe-sepa.php
  includes/payment-methods/class-wc-gateway-stripe-sofort.php
  webpack.config.js
Labels: pr: needs review, component: UPE, component: UPE settings

#1696 Currency-restricted UPE method admin notices
  includes/admin/class-wc-stripe-admin-notices.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-bancontact.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-eps.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-giropay.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-ideal.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
  tests/phpunit/admin/test-wc-stripe-admin-notices.php
Labels: pr: needs review, component: UPE

#1767 Enable SEPA IBAN field for UPE checkout
  client/classic/upe/index.js
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review, component: UPE
