Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2021-10, with the labels that each got.

#1969 Handle account data retrieval error
  includes/class-wc-stripe-account.php
Labels: pr: needs review, type: bug, component: UPE settings

#2017 fix: onboarding wizard page title
  includes/admin/class-wc-stripe-onboarding-controller.php
Labels: component: UPE settings

#2020 fix: Stripe controller naming conflict
  changelog.txt
  includes/admin/class-wc-rest-stripe-account-keys-controller.php
  includes/admin/class-wc-rest-stripe-settings-controller.php
  includes/admin/class-wc-stripe-rest-base-controller.php
  includes/admin/class-wc-stripe-rest-upe-flag-toggle-controller.php
  tests/phpunit/bootstrap.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#2011 feat: manual capture confirmation modal
  client/settings/payments-and-transactions-section/__tests__/manual-capture-control.test.js
  client/settings/payments-and-transactions-section/data-mock.js
  client/settings/payments-and-transactions-section/index.js
  client/settings/payments-and-transactions-section/manual-capture-control.js
Labels: pr: needs review, component: UPE settings

#2004 feat: account `wp/data` scaffolding
  client/data/account-keys/__tests__/actions.test.js
  client/data/account-keys/__tests__/hooks.test.js
  client/data/account-keys/__tests__/reducer.test.js
  client/data/account-keys/__tests__/selectors.test.js
  client/data/account-keys/action-types.js
  client/data/account-keys/actions.js
  client/data/account-keys/hooks.js
  client/data/account-keys/index.js
  client/data/account-keys/reducer.js
  client/data/account-keys/resolvers.js
  client/data/account-keys/selectors.js
  client/data/account/__tests__/actions.test.js
  client/data/account/__tests__/hooks.test.js
  client/data/account/__tests__/reducer.test.js
  client/data/account/__tests__/selectors.test.js
  client/data/account/action-types.js
  client/data/account/actions.js
  client/data/account/hooks.js
  client/data/account/index.js
  client/data/account/reducer.js
  client/data/account/resolvers.js
  client/data/account/selectors.js
  client/data/store.js
  includes/admin/class-wc-rest-stripe-account-controller.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#2023 fix: fatal error with Elementor+WooFunnels
  changelog.txt
  includes/migrations/class-allowed-payment-request-button-types-update.php
  tests/phpunit/admin/migrations/test-class-allowed-payment-request-button-types-update.php
  tests/phpunit/test-wc-stripe.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#2025 refactor: account data settings section
  client/data/settings/hooks.js
  client/settings/account-details/index.js
  client/settings/account-details/test/account-details.test.js
  client/settings/loadable-account-section.js
  client/settings/payment-settings/index.js
  includes/admin/class-wc-rest-stripe-settings-controller.php
  includes/admin/class-wc-stripe-settings-controller.php
  includes/class-wc-stripe-account.php
  tests/phpunit/admin/test-class-wc-stripe-settings-controller.php
  tests/phpunit/test-class-wc-stripe-account.php
Labels: component: UPE settings

#2024 feat: confirmation modal on test mode toggle
  client/data/settings/__tests__/actions.js
  client/data/settings/actions.js
  client/settings/__tests__/loadable-account-section.test.js
  client/settings/payment-settings/__tests__/general-settings-section.test.js
  client/settings/payment-settings/__tests__/test-mode-checkbox.test.js
  client/settings/payment-settings/general-settings-section.js
  client/settings/payment-settings/test-mode-checkbox.js
Labels: pr: needs review, component: UPE settings

#2030 Fix failed payments with empty source token
  changelog.txt
  client/data/settings/hooks.js
  client/settings/account-details/index.js
  client/settings/account-details/test/account-details.test.js
  client/settings/loadable-account-section.js
  client/settings/payment-settings/index.js
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/class-wc-rest-stripe-settings-controller.php
  includes/admin/class-wc-stripe-settings-controller.php
  includes/class-wc-stripe-account.php
  readme.txt
  tests/phpunit/admin/test-class-wc-stripe-settings-controller.php
  tests/phpunit/test-class-wc-stripe-account.php
Labels: pr: ready to merge

#2086 UPE - Pre-orders support
  changelog.txt
  client/blocks/upe/fields.js
  client/classic/upe/index.js
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/stripe-settings.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-helper.php
  includes/class-wc-stripe-webhook-handler.php
  includes/compat/trait-wc-stripe-pre-orders.php
  includes/payment-methods/class-wc-gateway-stripe-sepa.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
  readme.txt
  tests/phpunit/test-class-wc-stripe-upe-payment-gateway.php
  tests/phpunit/test-wc-stripe-sub-initial.php
  tests/phpunit/test-wc-stripe-sub-renewal.php
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#2106 UPE: Handle requires_confirmation status for PIs with saved cards
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: ready to merge, component: UPE
