Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2021-06, with the labels that each got.

#1588 Document why we use our AJAX API for the Payment Request integration with Blocks
  client/blocks/README.md
Labels: pr: ready to merge

#1585 Use shared configuration for shortcode- and block-based checkout flows
  changelog.txt
  client/api/index.js
  client/blocks/credit-card/index.js
  client/blocks/credit-card/payment-method.js
  client/blocks/credit-card/use-payment-processing.js
  client/blocks/payment-request/branded-buttons.js
  client/blocks/payment-request/custom-button.js
  client/blocks/payment-request/event-handlers.js
  client/blocks/payment-request/index.js
  client/blocks/payment-request/payment-request-express.js
  client/blocks/stripe-utils/load-stripe.js
  client/blocks/stripe-utils/normalize.js
  client/blocks/stripe-utils/type-defs.js
  client/blocks/stripe-utils/utils.js
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-blocks-support.php
  includes/class-wc-stripe-helper.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#1594 Check for the existence of the WC Cart before using it to generate JS configuration
  changelog.txt
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: pr: needs review

#1596 Check for any cart or checkout shortcode before enqueuing payment scripts
  changelog.txt
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-helper.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: pr: needs review

#1591 Hide Payment Request Buttons when cart contains multiple packages
  changelog.txt
  client/blocks/payment-request/index.js
  includes/class-wc-stripe-blocks-support.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: pr: needs author reply, pr: ready to merge

#1609 Payment Request Button: Guide users to authentication when it is required
  assets/js/stripe-payment-request.js
  changelog.txt
  client/blocks/payment-request/hooks.js
  client/blocks/payment-request/login-confirmation.js
  client/blocks/payment-request/payment-request-express.js
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: pr: needs review

#1603 Fix onClose event handler for Blocks
  assets/js/stripe-admin.min.js
  client/blocks/payment-request/hooks.js
Labels: pr: ready to merge
