Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2021-05, with the labels that each got.

#1509 Use triggers block/unblock the payment request button
  assets/js/stripe-payment-request.js
Labels: pr: ready to merge, status: blocked

#1533 Variable Products: Fix price when “Default form values” is set
  includes/payment-methods/class-wc-stripe-payment-request.php
Labels: pr: needs review

#1555 Fix subscription sign-up fees not showing up for Payment Request
  changelog.txt
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: pr: ready to merge

#1557 Handle "No such PaymentMethod" error on renewal
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
Labels: pr: ready to merge

#1544 Add psuedo random option for remote inbox note A/B tests
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#1560 Update woorelease config to include version replace paths
  package.json
Labels: pr: ready to merge

#1467 Add support for Cart and Checkout Blocks
  .babelrc
  .eslintignore
  .eslintrc
  .eslintrc.js
  .gitattributes
  .gitignore
  .prettierrc.js
  assets/css/stripe-styles.css
  assets/css/stripe-styles.scss
  assets/js/stripe-payment-request.js
  assets/js/stripe-payment-request.min.js
  assets/js/stripe.js
  assets/js/stripe.min.js
  changelog.txt
  client/api/index.js
  client/blocks/credit-card/constants.js
  client/blocks/credit-card/elements.js
  client/blocks/credit-card/index.js
  client/blocks/credit-card/payment-method.js
  client/blocks/credit-card/use-checkout-subscriptions.js
  client/blocks/credit-card/use-element-options.js
  client/blocks/credit-card/use-payment-processing.js
  client/blocks/index.js
  client/blocks/payment-request/apple-pay-preview.js
  client/blocks/payment-request/branded-buttons.js
  client/blocks/payment-request/constants.js
  client/blocks/payment-request/custom-button.js
  client/blocks/payment-request/event-handlers.js
  client/blocks/payment-request/hooks.js
  client/blocks/payment-request/index.js
  client/blocks/payment-request/payment-request-express.js
  client/blocks/stripe-utils/constants.js
  client/blocks/stripe-utils/index.js
  client/blocks/stripe-utils/load-stripe.js
  client/blocks/stripe-utils/normalize.js
  client/blocks/stripe-utils/type-defs.js
  client/blocks/stripe-utils/utils.js
  client/blocks/three-d-secure/index.js
  client/blocks/three-d-secure/three-d-secure-payment-handler.js
  client/blocks/three-d-secure/use-payment-intents.js
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-blocks-support.php
  includes/class-wc-stripe-helper.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  languages/woocommerce-gateway-stripe.pot
  package-lock.json
  package.json
  readme.txt
  tasks/release.js
  tests/phpunit/test-wc-stripe-helper.php
  webpack.config.js
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#1552 Address deprecations introduced in WC Admin v1.7.0
  changelog.txt
  includes/admin/class-wc-stripe-inbox-notes.php
  includes/compat/class-wc-stripe-woo-compat-utils.php
  readme.txt
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#1562 Only send requets to oauth when we are on the settings page
  changelog.txt
  includes/admin/stripe-settings.php
  includes/class-wc-gateway-stripe.php
Labels: pr: ready to merge

#1554 Add partner ID to API request header and exclude from filter
  includes/class-wc-stripe-api.php
Labels: pr: needs author reply

#1565 Add missing billing information to the stripe customer object during checkout with the Checkout Block
  client/blocks/credit-card/use-payment-processing.js
Labels: pr: ready to merge

#1567 Make sure Stripe blocks are rendered correctly in Gutenberg
  assets/js/stripe-payment-request.js
  assets/js/stripe-payment-request.min.js
  client/blocks/payment-request/index.js
  client/blocks/stripe-utils/load-stripe.js
  includes/class-wc-stripe-blocks-support.php
Labels: pr: needs review

#1582 Use createPaymentRequestUsingCart to check whether to show PRBs or not with Block-based checkout
  client/blocks/payment-request/index.js
Labels: pr: ready to merge
