Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2021-01, with the labels that each got.

#1263 Add to disallowed descriptor character list
  changelog.txt
  includes/admin/stripe-settings.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-helper.php
  languages/woocommerce-gateway-stripe.pot
  package-lock.json
  readme.txt
  tests/phpunit/test-wc-stripe.php
Labels: pr: ready to merge

#1447 Trim the refund reason to a max of 500 characters
  changelog.txt
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
Labels: pr: ready to merge

#1443 Fix Payment Request button for Puerto Rico and handle error for unsupported countries
  assets/js/stripe-payment-request.js
  assets/js/stripe-payment-request.min.js
  changelog.txt
  languages/woocommerce-gateway-stripe.pot
Labels: pr: ready to merge

#1437 Fixed Stripe disables webhook if multiple applications are connected to an account.
  includes/class-wc-stripe-webhook-handler.php
Labels: pr: needs review

#1226 Show warning when server time is off from device time
  assets/js/stripe-admin.js
  assets/js/stripe-admin.min.js
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-webhook-handler.php
  languages/woocommerce-gateway-stripe.pot
Labels: pr: needs author reply, pr: ready to merge

#1432 Add !empty check to avoid PHP notice
  includes/class-wc-stripe-intent-controller.php
Labels: pr: needs review
