Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2021-11, with the labels that each got.

#2095 Update test workflow to run for each WP/WC/PHP version supported
  .github/workflows/compatibility.yml
  .github/workflows/linting.yml
  .github/workflows/php-tests.yml
  composer.json
  composer.lock
  tests/phpunit/bootstrap.php
Labels: pr: needs review

#2068 Add new Stripe gateways UI
  client/data/index.js
  client/data/payment-gateway/__tests__/actions.test.js
  client/data/payment-gateway/__tests__/hooks.test.js
  client/data/payment-gateway/__tests__/reducer.test.js
  client/data/payment-gateway/__tests__/resolvers.test.js
  client/data/payment-gateway/__tests__/selectors.test.js
  client/data/payment-gateway/action-types.js
  client/data/payment-gateway/actions.js
  client/data/payment-gateway/hooks.js
  client/data/payment-gateway/index.js
  client/data/payment-gateway/reducer.js
  client/data/payment-gateway/resolvers.js
  client/data/payment-gateway/selectors.js
  client/data/store.js
  client/entrypoints/upe-opt-in-banner/index.js
  client/settings/index.js
  client/settings/loadable-payment-gateway-section.js
  client/settings/payment-gateway-manager/__tests__/index.test.js
  client/settings/payment-gateway-manager/constants.js
  client/settings/payment-gateway-manager/index.js
  client/settings/payment-gateway-manager/opt-in-banner-image.js
  client/settings/payment-gateway-manager/opt-in-banner.js
  client/settings/payment-gateway-section/__tests__/index.test.js
  client/settings/payment-gateway-section/index.js
  client/settings/save-payment-gateway-section/__tests__/index.test.js
  client/settings/save-payment-gateway-section/index.js
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/class-wc-rest-stripe-payment-gateway-controller.php
  includes/admin/class-wc-stripe-settings-controller.php
  includes/payment-methods/class-wc-gateway-stripe-bancontact.php
  includes/payment-methods/class-wc-gateway-stripe-eps.php
  includes/payment-methods/class-wc-gateway-stripe-giropay.php
  includes/payment-methods/class-wc-gateway-stripe-ideal.php
  includes/payment-methods/class-wc-gateway-stripe-p24.php
  includes/payment-methods/class-wc-gateway-stripe-sepa.php
  includes/payment-methods/class-wc-gateway-stripe-sofort.php
  tests/phpunit/admin/test-class-wc-rest-stripe-payment-gateway-controller.php
  tests/phpunit/test-wc-stripe-payment-gateway.php
  webpack.config.js
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#2107 Remove provide feedback link from upe settings
  client/settings/general-settings-section/section-heading.js
Labels: pr: needs review, component: UPE settings

#2109 Update min supported version numbers
  changelog.txt
  includes/admin/class-wc-stripe-admin-notices.php
  phpcs.xml.dist
  readme.txt
  tests/phpunit/admin/test-wc-stripe-admin-notices.php
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#2112 Alipay: Support MYR currency
  changelog.txt
  includes/payment-methods/class-wc-gateway-stripe-alipay.php
  readme.txt
Labels: pr: needs review

#2073 Feat / Account keys UI
  client/data/account-keys/actions.js
  client/settings/connect-stripe-account/__tests__/connect-stripe-account.test.js
  client/settings/connect-stripe-account/index.js
  client/settings/payment-settings/__tests__/general-settings-section.test.js
  client/settings/payment-settings/__tests__/test-mode-checkbox.test.js
  client/settings/payment-settings/account-keys-modal.js
  client/settings/payment-settings/general-settings-section.js
  client/settings/payment-settings/index.js
  client/settings/payment-settings/test-mode-checkbox.js
Labels: pr: ready to merge, component: UPE settings

#2116 Add launch config for debugging a local WP site with Xdebug in VSCode
  .vscode/launch.json
Labels: pr: ready to merge

#2108 add brazil to readme
  README.md
Labels: pr: needs review

#2127 Replace unsupported mysql image in Docker configuration
  docker-compose.yml
Labels: pr: ready to merge

#2110 Only load Stripe JS on product page when required
  changelog.txt
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-helper.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  package-lock.json
  readme.txt
Labels: pr: ready to merge

#2130 Add missing currency notice
  client/components/payment-method-missing-currency-pill/__tests__/index.test.js
  client/components/payment-method-missing-currency-pill/index.js
  client/settings/general-settings-section/payment-method-description.js
Labels: pr: ready to merge

#2134 Remove duplicate dependencies
  package.json
Labels: priority: low, pr: ready to merge

#2129 Add connection token API
  changelog.txt
  includes/admin/class-wc-rest-stripe-connection-tokens-controller.php
  tests/phpunit/admin/test-class-wc-rest-stripe-connection-tokens-controller.php
  woocommerce-gateway-stripe.php
Labels: pr: needs author reply

#2138 Update readme and changelog to remove pre-release preview for new settings
  changelog.txt
  readme.txt
Labels: pr: ready to merge

#2139 Fix selector name
  client/data/payment-gateway/selectors.js
Labels: pr: ready to merge

#2140 Fix / Allow statement descriptor to be empty
  includes/admin/class-wc-rest-stripe-settings-controller.php
Labels: pr: needs review

#2142 Reload page after saving keys
  client/settings/connect-stripe-account/index.js
  client/settings/payment-settings/account-keys-modal.js
  client/settings/payment-settings/general-settings-section.js
  client/settings/payment-settings/index.js
  client/settings/payment-settings/test-mode-checkbox.js
  client/settings/settings-manager/index.js
  includes/admin/class-wc-rest-stripe-account-keys-controller.php
Labels: pr: ready to merge

#2133 Add WP_UnitTestCase stub
  tests/phpunit/wp-unit-test-case.php
Labels: priority: low, pr: ready to merge

#2144 Add support for Stripe Location API
  changelog.txt
  includes/admin/class-wc-rest-stripe-locations-controller.php
  tests/phpunit/admin/test-class-wc-rest-stripe-locations-controller.php
  woocommerce-gateway-stripe.php
Labels: status: has pr

#2146 Allow customization of the payment method title
  client/data/settings/hooks.js
  client/settings/payment-settings/__tests__/general-settings-section.test.js
  client/settings/payment-settings/general-settings-section.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/enable-upe-preview-task.js
  includes/admin/class-wc-rest-stripe-settings-controller.php
Labels: pr: ready to merge

#2160 Reload page while keeping "Disconnect Stripe account" modal open after submit
  client/settings/loadable-account-section.js
  client/settings/payment-settings/__tests__/disconnect-stripe-confirmation-modal.test.js
  client/settings/payment-settings/disconnect-stripe-confirmation-modal.js
  client/settings/payment-settings/index.js
Labels: pr: needs review

#2128 Hide PRB when all variations are out-of-stock
  assets/js/stripe-payment-request.js
  changelog.txt
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: pr: ready to merge

#2155 Update documentation links
  includes/admin/class-wc-stripe-admin-notices.php
  includes/admin/class-wc-stripe-inbox-notes.php
  includes/admin/class-wc-stripe-privacy.php
  includes/admin/stripe-settings.php
  languages/woocommerce-gateway-stripe.pot
  readme.txt
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#2143 Update pending activation flow and hide UPE payment methods when not available
  client/components/payment-method-capability-status-pill/__tests__/payment-method-capability-status-pill.test.js
  client/components/payment-method-capability-status-pill/index.js
  client/settings/general-settings-section/__tests__/disable-upe-confirmation-modal.test.js
  client/settings/general-settings-section/__tests__/general-settings-section.test.js
  client/settings/general-settings-section/disable-upe-confirmation-modal.js
  client/settings/general-settings-section/payment-methods-list.js
  client/settings/general-settings-section/section-footer.js
  client/settings/payment-gateway-manager/constants.js
  client/settings/payment-gateway-manager/index.js
  client/settings/payment-gateway-section/__tests__/index.test.js
  client/settings/payment-gateway-section/index.js
  client/upe-onboarding-wizard/__tests__/onboarding-wizard.test.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/__tests__/add-payment-methods-task.test.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/__tests__/enable-upe-preview-task.test.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/add-payment-methods-task.js
Labels: pr: ready to merge

#2164 Revert "Hide PRB when all variations are out-of-stock"
  assets/js/stripe-payment-request.js
  changelog.txt
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: pr: ready to merge

#2165 Hide PRB when all variations are out-of-stock
  assets/js/stripe-payment-request.js
  changelog.txt
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: pr: ready to merge

#2157 Add requires currency notice in onboarding and APMs
  client/components/payment-method-missing-currency-pill/__tests__/index.test.js
  client/components/payment-method-missing-currency-pill/index.js
  client/payment-methods-map.js
  client/settings/payment-gateway-section/index.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/payment-method-checkbox/index.js
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: ready to merge, status: blocked

#2162 Add Invalid keys notice
  includes/admin/class-wc-stripe-admin-notices.php
  tests/phpunit/admin/test-wc-stripe-admin-notices.php
Labels: pr: ready to merge, component: UPE settings

#2158 Refactor Stripe Account Keys modal behavior
  client/settings/account-details/__tests__/account-details.test.js
  client/settings/account-details/index.js
  client/settings/connect-stripe-account/index.js
  client/settings/payment-settings/__tests__/test-mode-checkbox.test.js
  client/settings/payment-settings/account-keys-modal.js
  client/settings/payment-settings/general-settings-section.js
  client/settings/payment-settings/index.js
  client/settings/payment-settings/test-mode-checkbox.js
  includes/admin/class-wc-rest-stripe-account-controller.php
  includes/admin/class-wc-rest-stripe-account-keys-controller.php
  includes/admin/class-wc-stripe-admin-notices.php
  includes/admin/class-wc-stripe-settings-controller.php
  tests/phpunit/admin/test-wc-stripe-admin-notices.php
Labels: pr: ready to merge, component: UPE settings

#2171 Replace trim with ! empty
  includes/admin/class-wc-stripe-settings-controller.php
Labels: component: UPE settings

#2172 Hide short descriptor fields for release 5.8.0
  client/settings/payments-and-transactions-section/index.js
Labels: component: UPE settings

#2179 Run filters to disable Stripe JS when PRBs are disabled
  changelog.txt
  includes/class-wc-stripe-helper.php
  readme.txt
Labels: pr: needs review

#2177 Bump latest supported version for woocommerce
  .github/workflows/php-tests.yml
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#2194 Remove [ and ] from the status check name
  .github/workflows/php-tests.yml
Labels: pr: in progress

#2159 Add REST API to create customer for an order
  changelog.txt
  includes/admin/class-wc-rest-stripe-orders-controller.php
  tests/phpunit/admin/test-class-wc-rest-stripe-orders-controller.php
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#2115 Add Boleto and OXXO
  assets/css/stripe-styles.css
  assets/css/stripe-styles.scss
  assets/images/boleto.svg
  assets/images/oxxo.svg
  assets/js/jquery.mask.js
  assets/js/jquery.mask.min.js
  assets/js/stripe-payment-request.min.js
  assets/js/stripe.js
  assets/js/stripe.min.js
  changelog.txt
  client/blocks/upe/fields.js
  client/classic/upe/index.js
  client/payment-method-icons/boleto/icon.svg
  client/payment-method-icons/boleto/index.js
  client/payment-method-icons/oxxo/icon.svg
  client/payment-method-icons/oxxo/index.js
  client/payment-methods-map.js
  client/settings/payment-gateway-manager/constants.js
  includes/abstracts/abstract-wc-stripe-payment-gateway-voucher.php
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/class-wc-rest-stripe-payment-gateway-controller.php
  includes/admin/class-wc-stripe-admin-notices.php
  includes/admin/class-wc-stripe-settings-controller.php
  includes/admin/stripe-boleto-settings.php
  includes/admin/stripe-oxxo-settings.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-helper.php
  includes/class-wc-stripe-intent-controller.php
  includes/class-wc-stripe-webhook-handler.php
  includes/payment-methods/class-wc-gateway-stripe-alipay.php
  includes/payment-methods/class-wc-gateway-stripe-bancontact.php
  includes/payment-methods/class-wc-gateway-stripe-boleto.php
  includes/payment-methods/class-wc-gateway-stripe-eps.php
  includes/payment-methods/class-wc-gateway-stripe-giropay.php
  includes/payment-methods/class-wc-gateway-stripe-ideal.php
  includes/payment-methods/class-wc-gateway-stripe-multibanco.php
  includes/payment-methods/class-wc-gateway-stripe-oxxo.php
  includes/payment-methods/class-wc-gateway-stripe-p24.php
  includes/payment-methods/class-wc-gateway-stripe-sepa.php
  includes/payment-methods/class-wc-gateway-stripe-sofort.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-boleto.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-oxxo.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
  tests/manual/stripe-boleto.md
  tests/manual/stripe-oxxo.md
  tests/phpunit/test-class-wc-stripe-upe-payment-gateway.php
  tests/phpunit/test-class-wc-stripe-upe-payment-method.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#2166 Remove `_wcstripe_feature_upe` flag and all traces of old settings
  assets/css/stripe-admin-styles.css
  assets/css/stripe-admin-styles.scss
  assets/js/stripe-admin.js
  changelog.txt
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/class-wc-stripe-settings-controller.php
  includes/admin/class-wc-stripe-upe-compatibility-controller.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-feature-flags.php
  includes/notes/class-wc-stripe-upe-compatibility-note.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  readme.txt
  tests/phpunit/test-class-wc-stripe-notes.php
  tests/phpunit/test-wc-stripe-payment-gateway.php
  tests/phpunit/test-wc-stripe-upe-compatibility-controller.php
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#2209 fixed unhandled php error when invalid card is used on Pay Order page
  changelog.txt
  includes/class-wc-gateway-stripe.php
Labels: pr: needs review

#2208 fixed bug that would send stripe outdated data from blocks checkout
  changelog.txt
  client/blocks/upe/fields.js
Labels: pr: needs review

#2185 Replace word 'deposits' for 'payouts'
  client/settings/account-details/__tests__/account-details.test.js
  client/settings/account-details/index.js
  client/settings/payments-and-transactions-section/index.js
  client/settings/settings-manager/__tests__/index.test.js
Labels: pr: needs review

#2200 Add account summary API endpoint
  changelog.txt
  includes/admin/class-wc-rest-stripe-account-controller.php
  includes/class-wc-stripe-account.php
  tests/phpunit/test-class-wc-stripe-account.php
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge
