Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2021-07, with the labels that each got.

#1597 Payment Request button: Various Improvements
  assets/js/stripe-payment-request.js
  includes/payment-methods/class-wc-stripe-payment-request.php
Labels: pr: needs review

#1602 Payment Request button changes
  assets/js/stripe-payment-request.js
  changelog.txt
  client/blocks/payment-request/index.js
  client/blocks/stripe-utils/utils.js
  includes/admin/stripe-settings.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  tests/phpunit/test-wc-stripe-payment-request.php
Labels: pr: in progress

#1616 Fix SCA verification on free trial using Checkout block
  client/blocks/three-d-secure/use-payment-intents.js
Labels: pr: ready to merge

#1613 Fix early renew modal stuck loading and error
  assets/js/stripe.js
Labels: pr: needs author reply

#1642 [Payment Request Button] Do not ask for Shipping Address if no Shipping Zone is defined
  changelog.txt
  includes/payment-methods/class-wc-stripe-payment-request.php
Labels: pr: needs author reply

#1643 Release version 5.3.0
  changelog.txt
  client/blocks/three-d-secure/use-payment-intents.js
  includes/payment-methods/class-wc-stripe-payment-request.php
  package-lock.json
  package.json
  readme.txt
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#1648 UPE: Extract Stripe Api wrapper to a separate file
  client/classic/api.js
  client/classic/config.js
  client/classic/upe.js
  client/utils/index.js
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: in progress

#1652 Update PR template with testing instruction guidelines
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr: needs review
