Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2021-09, with the labels that each got.

#1747 Pass missing $post object to filter callbacks
  includes/payment-methods/class-wc-stripe-payment-request.php
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#1764 Add UPE opt-in banner in stripe settings page
  client/settings/general-settings-section/__tests__/general-settings-section.test.js
  client/settings/general-settings-section/index.js
  client/settings/upe-opt-in-banner/index.js
Labels: pr: needs review

#1779 Fix UPE on Pay for Order page
  client/api/index.js
  includes/class-wc-stripe-intent-controller.php
  includes/class-wc-stripe-order-handler.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: ready to merge

#1791 feat: add payments settings section
  client/settings/advanced-settings-section/__tests__/index.test.js
  client/settings/advanced-settings-section/data-mock.js
  client/settings/advanced-settings-section/debug-mode.js
  client/settings/advanced-settings-section/index.js
  client/settings/payment-settings/index.js
  client/settings/payments-and-transactions-section/__tests__/index.test.js
  client/settings/payments-and-transactions-section/__tests__/text-length-help-input-wrapper.test.js
  client/settings/payments-and-transactions-section/data-mock.js
  client/settings/payments-and-transactions-section/index.js
  client/settings/payments-and-transactions-section/text-length-help-input-wrapper.js
  package-lock.json
  package.json
Labels: pr: needs review

#1798 chore: UPE case consistency
  client/settings/general-settings-section/index.js
  client/settings/upe-opt-in-banner/__tests__/upe-opt-in-banner.test.js
  client/settings/upe-opt-in-banner/index.js
Labels: pr: needs review

#1711 Enable UPE in `Add payment method` page
  client/api/index.js
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/class-wc-stripe-customer.php
  includes/class-wc-stripe-intent-controller.php
  includes/class-wc-stripe-order-handler.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-bancontact.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-ideal.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
Labels: pr: needs review, component: UPE

#1777 Add SEPA UPE payment method
  includes/payment-methods/class-wc-gateway-stripe-sepa.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-sepa.php
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge, component: UPE

#1801 feat: payments accepted section
  client/components/confirmation-modal/index.js
  client/components/confirmation-modal/style.scss
  client/components/payment-method-fees-pill/index.js
  client/components/pill/index.js
  client/settings/general-settings-section/__tests__/disable-upe-confirmation-modal.test.js
  client/settings/general-settings-section/__tests__/general-settings-section.test.js
  client/settings/general-settings-section/data-mock.js
  client/settings/general-settings-section/disable-upe-confirmation-modal.js
  client/settings/general-settings-section/index.js
  client/settings/general-settings-section/payment-method-description.js
  client/settings/general-settings-section/payment-method-setup-help.js
  client/settings/general-settings-section/section-heading.js
  client/settings/payment-methods/index.js
  client/settings/upe-opt-in-banner/index.js
  package-lock.json
  package.json
Labels: pr: needs review

#1794 Feature: Add customization options notice
  .eslintrc.js
  client/components/inline-notice/index.js
  client/components/inline-notice/style.scss
  client/settings/customization-option-notice/__tests__/customization-options-notice.test.js
  client/settings/customization-option-notice/index.js
  client/settings/payment-methods/index.js
  client/settings/payment-settings/index.js
  client/settings/settings-manager/__tests__/index.test.js
Labels: pr: needs review, needs tests

#1788 Filter out payment methods which do not support current currency
  includes/class-wc-stripe-intent-controller.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
Labels: pr: ready to merge

#1803 feat: onboarding UPE enable
  client/settings/upe-opt-in-banner/index.js
  client/upe-onboarding-wizard/index.js
  client/upe-onboarding-wizard/onboarding-wizard.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/__tests__/enable-upe-preview-task.test.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/enable-upe-preview-task.js
  includes/admin/class-wc-stripe-onboarding-controller.php
Labels: pr: needs review

#1819 fix: customization options notice destructure
  client/components/inline-notice/style.scss
  client/settings/customization-options-notice/__tests__/customization-options-notice.test.js
  client/settings/customization-options-notice/index.js
  client/settings/payment-methods/index.js
  client/settings/payment-settings/index.js
  client/settings/settings-manager/__tests__/index.test.js
  package-lock.json
  package.json
Labels: pr: needs review

#1823 refactor: UPE banner content
  client/components/inline-notice/index.js
  client/components/inline-notice/style.scss
  client/entrypoints/upe-opt-in-banner/all-payment-methods/index.js
  client/entrypoints/upe-opt-in-banner/index.js
  client/payment-method-icons/all-payment-methods/icon.svg
  client/payment-method-icons/all-payment-methods/index.js
  client/settings/general-settings-section/index.js
  client/settings/general-settings-section/upe-opt-in-banner.js
  client/settings/upe-opt-in-banner/__tests__/upe-opt-in-banner.test.js
  client/settings/upe-opt-in-banner/index.js
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  webpack.config.js
Labels: pr: needs review

#1832 fix: payment request domain name
  client/settings/payment-requests/payment-request-customizer.js
  client/settings/payment-requests/payment-request-settings.js
Labels: pr: needs review

#1762 Feature: Add UPE availability inbox notice
  includes/admin/class-wc-stripe-inbox-notes.php
  includes/notes/class-wc-stripe-upe-availability-note.php
  tests/phpunit/test-class-wc-stripe-notes.php
  tests/phpunit/test-class-wc-stripe-upe-availability-note.php
Labels: pr: needs review

#1833 chore: add survey emoji
  client/settings/general-settings-section/disable-upe-confirmation-modal.js
Labels: pr: needs review

#1841 chore: remove inbox notice when UPE enabled
  includes/admin/class-wc-rest-upe-flag-toggle-controller.php
Labels: pr: needs review

#1844 refactor: general settings section styles
  client/settings/payment-settings/__tests__/general-settings-section.test.js
  client/settings/payment-settings/general-settings-section.js
Labels: pr: needs review

#1842 refactor: keep track of UPE disabled
  includes/admin/class-wc-rest-upe-flag-toggle-controller.php
  includes/class-wc-stripe-feature-flags.php
  includes/notes/class-wc-stripe-upe-availability-note.php
  tests/phpunit/test-class-wc-stripe-notes.php
  tests/phpunit/test-wc-rest-upe-flag-toggle-controller.php
Labels: pr: needs review

#1849 Prepare header and changelog for 5.5.0 release
  readme.txt
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#1789 Add support for manually capturing charges in UPE
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-intent-controller.php
  includes/payment-methods/class-wc-gateway-stripe-sepa.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  tests/phpunit/test-wc-stripe-intent-controller.php
Labels: pr: needs review, component: UPE

#1864 fix: prevent scripts queue when not necessary
  includes/admin/class-wc-stripe-onboarding-controller.php
Labels: pr: needs review

#1847 feat: payment request page data persist
  client/components/loadable-settings-section/index.js
  client/data/settings/__tests__/hooks.js
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/entrypoints/payment-request-settings/__tests__/payment-request-button-preview.test.js
  client/entrypoints/payment-request-settings/__tests__/payment-request-section.test.js
  client/entrypoints/payment-request-settings/index.js
  client/entrypoints/payment-request-settings/payment-request-button-preview.js
  client/entrypoints/payment-request-settings/payment-request-page.js
  client/entrypoints/payment-request-settings/payment-request-section.js
  client/entrypoints/payment-request-settings/style.scss
  client/entrypoints/payment-request-settings/utils/utils.js
  includes/admin/class-wc-rest-stripe-settings-controller.php
  includes/admin/class-wc-stripe-payment-requests-controller.php
  includes/admin/stripe-settings.php
  package-lock.json
  package.json
  tests/phpunit/admin/test-class-wc-rest-stripe-settings-controller.php
  webpack.config.js
Labels: pr: needs review

#1862 refactor: setup needed messaging
  client/settings/general-settings-section/index.js
  client/settings/general-settings-section/payment-method-description.js
  client/settings/general-settings-section/payment-method-setup-help.js
Labels: pr: needs review

#1774 Add "Connect Stripe Account" UI
  client/payment-method-icons/stripe-banner/icon.svg
  client/payment-method-icons/stripe-banner/index.js
  client/settings/connect-stripe-account/__tests__/connect-stripe-account.test.js
  client/settings/connect-stripe-account/index.js
  client/settings/index.js
  client/settings/styles.scss
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/class-wc-stripe-admin-notices.php
  includes/admin/class-wc-stripe-settings-controller.php
  tests/phpunit/admin/test-class-wc-stripe-settings-controller.php
  tests/phpunit/admin/test-wc-stripe-admin-notices.php
  tests/phpunit/test-wc-stripe-payment-gateway.php
Labels: pr: needs review

#1856 Move the UPE action hooks to the IntentsController
  includes/class-wc-stripe-intent-controller.php
  includes/class-wc-stripe-order-handler.php
Labels: pr: needs review, component: UPE

#1851 Show count of enabled payment methods in main settings page
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review

#1886 chore: add additional payment methods
  client/payment-method-icons/bancontact/icon.svg
  client/payment-method-icons/bancontact/index.js
  client/payment-method-icons/eps/icon.svg
  client/payment-method-icons/eps/index.js
  client/payment-method-icons/ideal/icon.svg
  client/payment-method-icons/ideal/index.js
  client/payment-methods-map.js
Labels: pr: needs review, component: UPE settings

#1881 feat: stripe banner on onboarding
  client/components/payment-methods-checkboxes/payment-method-checkbox.js
  client/components/payment-methods-checkboxes/style.scss
  client/components/stripe-banner/icon.svg
  client/components/stripe-banner/index.js
  client/payment-method-icons/stripe-banner/index.js
  client/settings/connect-stripe-account/index.js
  client/upe-onboarding-wizard/onboarding-wizard.js
Labels: pr: needs review, component: UPE settings

#1885 chore: fetch settings on UPE toggle
  client/settings/upe-toggle/__tests__/provider.test.js
  client/settings/upe-toggle/provider.js
Labels: pr: needs review, component: UPE settings

#1882 Revert getting the Stripe gateway from the list of enabled gateways
  includes/class-wc-stripe-intent-controller.php
Labels: pr: needs review

#1884 feat: express payment methods with new settings
  includes/payment-methods/class-wc-stripe-payment-request.php
Labels: pr: needs review, component: UPE settings

#1883 feat: express checkout options migration
  includes/migrations/class-allowed-payment-request-button-types-update.php
  tests/phpunit/admin/migrations/test-class-allowed-payment-request-button-types-update.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#1902 fix: variables import path
  client/styles/abstracts/styles.scss
Labels: pr: needs review

#1880 refactor: payment methods list
  client/components/tooltip/index.js
  client/settings/card-body.js
  client/settings/card-footer.js
  client/settings/general-settings-section/__tests__/general-settings-section.test.js
  client/settings/general-settings-section/index.js
  client/settings/general-settings-section/payment-method-description.js
  client/settings/general-settings-section/payment-method-setup-help.js
  client/settings/general-settings-section/payment-methods-list.js
  client/settings/general-settings-section/section-footer.js
  client/settings/general-settings-section/section-heading.js
  client/settings/payment-settings/general-settings-section.js
Labels: pr: needs review, component: UPE settings

#1887 feat: payment methods availability
  client/components/payment-methods-checkboxes/payment-method-checkbox.js
  client/components/payment-methods-checkboxes/style.scss
  client/data/settings/__tests__/hooks.js
  client/data/settings/hooks.js
  client/settings/general-settings-section/__tests__/disable-upe-confirmation-modal.test.js
  client/settings/general-settings-section/__tests__/general-settings-section.test.js
  client/settings/general-settings-section/data-mock.js
  client/settings/general-settings-section/disable-upe-confirmation-modal.js
  client/settings/general-settings-section/payment-methods-list.js
  client/settings/payment-method-icon/index.js
  client/upe-onboarding-wizard/style.scss
  client/upe-onboarding-wizard/upe-preview-methods-selector/__tests__/add-payment-methods-task.test.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/__tests__/setup-complete-task.test.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/add-payment-methods-task.js
  client/upe-onboarding-wizard/upe-preview-methods-selector/setup-complete-task.js
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/class-wc-rest-stripe-settings-controller.php
Labels: pr: needs review

#1906 Show payment method description
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-bancontact.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-cc.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-eps.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-giropay.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-ideal.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-sepa.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
Labels: pr: needs review

#1890 chore: disable method fees
  .eslintrc.js
  client/components/payment-method-fees-pill/__tests__/index.test.js
  client/components/payment-method-fees-pill/index.js
  package-lock.json
  package.json
  tests/js/jest-setup.js
  tests/js/jest.config.js
  webpack.config.js
Labels: pr: needs review

#1871 Adds statement previews for full and shortened bank statement text.
  client/settings/payments-and-transactions-section/__tests__/index.test.js
  client/settings/payments-and-transactions-section/index.js
  client/settings/payments-and-transactions-section/statement-preview/icons/bank.js
  client/settings/payments-and-transactions-section/statement-preview/icons/creditCard.js
  client/settings/payments-and-transactions-section/statement-preview/index.js
  client/settings/payments-and-transactions-section/statement-preview/style.scss
  client/settings/payments-and-transactions-section/statement-previews-wrapper.js
  package-lock.json
  package.json
Labels: pr: needs review

#1891 Hide/disable UPE when preorders plugin is active
  includes/admin/stripe-settings.php
  includes/class-wc-stripe-helper.php
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#1907 [UPE - old settings] Move express checkout size option to PRB section
  includes/admin/stripe-settings.php
Labels: pr: needs review, component: UPE settings

#1911 feat: currency needed messaging
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
Labels: pr: needs review

#1913 feat: survey prompt on UPE disable
  client/entrypoints/old-settings-upe-toggle/index.js
  includes/admin/class-wc-stripe-old-settings-upe-toggle-controller.php
  webpack.config.js
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#1926 Provide default.env file to wp command
  package.json
Labels: pr: needs review

#1915 Track upe toggle in old settings page
  client/entrypoints/old-settings-upe-toggle/index.js
Labels: pr: needs review

#1921 chore: add P24 & Sofort to UPE
  client/payment-method-icons/p24/icon.svg
  client/payment-method-icons/p24/index.js
  client/payment-methods-map.js
  includes/payment-methods/class-wc-gateway-stripe-p24.php
  includes/payment-methods/class-wc-gateway-stripe-sofort.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-p24.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-sofort.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#1922 chore: remove UPE note on deactivation
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#1908 Use original gateway to process payment request buttons from UPE
  client/classic/upe/index.js
  client/classic/upe/legacy-support.js
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review

#1916 [UPE - settings] Add capabilities messaging for payment methods
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
Labels: pr: needs review, component: UPE settings

#1935 fix: dupe payment request height
  assets/js/stripe-admin.js
  assets/js/stripe-admin.min.js
  includes/admin/stripe-settings.php
Labels: pr: needs review

#1932 Adds "Disable Stripe" confirmation modal
  client/entrypoints/payment-gateways/__tests__/index.test.js
  client/entrypoints/payment-gateways/disable-confirmation-modal.js
  client/entrypoints/payment-gateways/index.js
  client/entrypoints/payment-gateways/payment-gateways-confirmation.js
  client/entrypoints/payment-gateways/style.scss
  includes/admin/class-wc-stripe-payment-gateways-controller.php
  webpack.config.js
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#1937 fix: UPE note when account disconnected
  includes/notes/class-wc-stripe-upe-availability-note.php
  tests/phpunit/test-class-wc-stripe-notes.php
Labels: pr: needs review

#1836 UPE Subscriptions support
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-intent-controller.php
  includes/compat/class-wc-stripe-sepa-subs-compat.php
  includes/compat/trait-wc-stripe-subscriptions-utilities.php
  includes/compat/trait-wc-stripe-subscriptions.php
  includes/payment-methods/class-wc-gateway-stripe-sepa.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-bancontact.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-ideal.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
  tests/phpunit/test-class-wc-stripe-upe-payment-gateway.php
  tests/phpunit/test-wc-stripe-sub-initial.php
  tests/phpunit/test-wc-stripe-sub-renewal.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#1947 Fix error when account is created during checkout
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review

#1938 chore: add require-await eslint rule
  .eslintrc.js
  client/entrypoints/payment-gateways/__tests__/index.test.js
  client/settings/payment-request-section/__tests__/index.test.js
Labels: pr: ready to merge

#1903 chore: update SSO TOS link
  client/settings/connect-stripe-account/__tests__/connect-stripe-account.test.js
  client/settings/connect-stripe-account/index.js
Labels: pr: needs review

#1936 fix: UPE banner eligibility
  includes/payment-methods/class-wc-gateway-stripe-alipay.php
  includes/payment-methods/class-wc-gateway-stripe-multibanco.php
Labels: pr: needs review, component: UPE settings

#1951 Remove the payment method links inside Stripe UPE
  assets/css/stripe-admin-styles.css
  assets/css/stripe-admin-styles.scss
  includes/admin/class-wc-stripe-settings-controller.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  package.json
Labels: pr: needs review

#1946 Use custom title setting for UPE blocks
  client/blocks/upe/payment-method.js
Labels: pr: needs review, status: blocked

#1958 Change method name from `Stripe UPE` to `Stripe`
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review

#1869 Retrieve real account status
  client/settings/payment-settings/index.js
  client/settings/settings-manager/__tests__/index.test.js
  includes/admin/class-wc-stripe-settings-controller.php
  includes/class-wc-stripe-account.php
  tests/phpunit/admin/test-class-wc-stripe-settings-controller.php
  tests/phpunit/bootstrap.php
  tests/phpunit/helpers/class-wc-helper-stripe-api.php
  tests/phpunit/test-class-wc-stripe-account.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#1961 Remove method count text when no method is enabled
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review

#1965 Set UPE preview feature flag default value to `yes`
  changelog.txt
  includes/class-wc-stripe-feature-flags.php
  readme.txt
  tests/phpunit/test-wc-rest-upe-flag-toggle-controller.php
Labels: pr: needs review

#1904 UPE - Support free trial subscriptions
  client/api/index.js
  client/blocks/upe/fields.js
  client/classic/upe/index.js
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review

#1950 Force the UPE toggle option value to 'no' if not set
  includes/admin/class-wc-stripe-payment-gateways-controller.php
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#1963 Update the UPE Gateway title in the checkout depending the enabled methods
  includes/admin/stripe-settings.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-blocks-support.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  tests/phpunit/test-class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review, component: UPE

#1957 Fix warning message on settings page
  includes/admin/class-wc-stripe-payment-gateways-controller.php
Labels: pr: needs review, type: bug

#1949 [UPE - settings] Update manual capture implementation on enabled payment methods
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review, component: UPE settings

#1924 feat: checks on notice compatibility
  includes/admin/class-wc-rest-upe-flag-toggle-controller.php
  includes/admin/class-wc-stripe-inbox-notes.php
  includes/admin/class-wc-stripe-upe-compatibility-controller.php
  includes/class-wc-stripe-upe-compatibility.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#1959 refactor: confirmation modal heading reuse
  client/components/confirmation-modal/alert-title.js
  client/entrypoints/payment-gateways/disable-confirmation-modal.js
  client/entrypoints/payment-gateways/style.scss
  client/settings/general-settings-section/disable-upe-confirmation-modal.js
Labels: pr: needs review, component: UPE settings

#1962 fix: gradient on carte bancaire
  client/payment-method-icons/cards/icon.svg
Labels: pr: needs review

#1971 fix: payment request options update
  includes/admin/stripe-settings.php
Labels: pr: needs review

#1978 fix: UPE controller name clash
  includes/admin/class-wc-stripe-rest-upe-flag-toggle-controller.php
  tests/phpunit/test-wc-rest-upe-flag-toggle-controller.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review, component: UPE settings

#1979 Fix misaligned credit card icons
  assets/css/stripe-styles.css
  assets/css/stripe-styles.scss
  assets/js/stripe.js
  changelog.txt
  includes/class-wc-gateway-stripe.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  readme.txt
Labels: pr: needs review

#1996 Add mandate data to setup intents created with saved payment method
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-bancontact.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-ideal.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-sofort.php
Labels: pr: needs review

#1995 Add notice to merchants about disabled payment methods
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review, component: UPE settings

#1982 Enable payment methods when enabling/disabling UPE
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#1999 Add spacing after UPE container on checkout.
  client/classic/upe/style.scss
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review

#2003 Keep the enabled payment methods for UPE in the config when disabling the UPE gateway
  tests/phpunit/admin/test-wc-stripe-admin-notices.php
  woocommerce-gateway-stripe.php
Labels: component: UPE

#1986 'Remove method' confirmation modal
  client/settings/general-settings-section/__tests__/general-settings-section.test.js
  client/settings/general-settings-section/__tests__/remove-method-confirmation-modal.test.js
  client/settings/general-settings-section/payment-methods-list.js
  client/settings/general-settings-section/remove-method-confirmation-modal.js
Labels: pr: needs review
