Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2022-07, with the labels that each got.

#2375 Add stripe link headers to requests
  changelog.txt
  client/api/index.js
  readme.txt
Labels: pr: needs review

#2370 StripeLink: Add payment method option in admin
  changelog.txt
  client/payment-method-icons/link/icon.svg
  client/payment-method-icons/link/index.js
  client/payment-methods-map.js
  client/settings/general-settings-section/__tests__/general-settings-section.test.js
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-link.php
  readme.txt
  tests/phpunit/admin/test-class-wc-rest-stripe-settings-controller.php
  tests/phpunit/test-class-wc-stripe-upe-payment-method.php
  tests/phpunit/test-wc-stripe.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#2382 add payment method on checkout form
  changelog.txt
  client/api/index.js
  client/classic/upe/index.js
  client/stripe-link/index.js
  client/styles/upe/__tests__/index.js
  client/styles/upe/index.js
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  readme.txt
Labels: pr: needs review

#2388 Add Stripe Link button if email is pre-filled
  assets/css/stripe-link.css
  client/stripe-link/index.js
Labels: pr: needs review

#2387 remove feature flag
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  tests/phpunit/admin/test-class-wc-rest-stripe-settings-controller.php
Labels: pr: ready to merge, status: blocked

#2386 Add StripeLink to WooCommerce Checkout block
  changelog.txt
  client/blocks/credit-card/constants.js
  client/blocks/upe/fields.js
  client/blocks/upe/styles.scss
  client/classic/upe/index.js
  client/stripe-link/index.js
  includes/class-wc-stripe-blocks-support.php
  includes/class-wc-stripe-intent-controller.php
  readme.txt
Labels: pr: needs review

#2390 Add pre-push hook when pushing to develop, trunk and release branches
  .husky/pre-push
Labels: pr: ready to merge, type: task
