Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2022-01, with the labels that each got.

#2266 Merge trunk from 6.0.0
  changelog.txt
  package-lock.json
  package.json
  readme.txt
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#2257 Add allow-plugins entry to composer config
  composer.json
  package-lock.json
Labels: pr: needs review, type: technical debt

#2251 Add a filter call when updating an existent intent (saved in the order)
  changelog.txt
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  readme.txt
Labels: pr: needs review

#2273 Account Keys Connection Status
  changelog.txt
  client/data/account-keys/__tests__/actions.test.js
  client/data/account-keys/__tests__/hooks.test.js
  client/data/account-keys/__tests__/reducer.test.js
  client/data/account-keys/action-types.js
  client/data/account-keys/actions.js
  client/data/account-keys/hooks.js
  client/data/account-keys/reducer.js
  client/data/account-keys/selectors.js
  client/data/account/__tests__/actions.test.js
  client/data/account/actions.js
  client/data/store.js
  client/settings/payment-settings/__tests__/general-settings-section.test.js
  client/settings/payment-settings/account-keys-connection-status.js
  client/settings/payment-settings/account-keys-modal.js
  client/settings/payment-settings/style.scss
  client/settings/upe-toggle/provider.js
  includes/admin/class-wc-rest-stripe-tokens-controller.php
  readme.txt
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#2278 Load xdebug on demand for VSCode and Docker
  .vscode/launch.json
  .vscode/tasks.json
  docker-compose.yml
  docker/wordpress_xdebug/Dockerfile
  package.json
Labels: pr: needs author reply

#2283 Fix full bank statement field description
  changelog.txt
  client/settings/payments-and-transactions-section/index.js
  client/settings/payments-and-transactions-section/text-length-help-input-wrapper.js
  includes/class-wc-gateway-stripe.php
  readme.txt
Labels: pr: ready to merge

#2272 Add is_live and test_mode to account summary API
  changelog.txt
  includes/admin/class-wc-rest-stripe-account-controller.php
  readme.txt
Labels: pr: ready to merge

#2275 Fix account summary API response when no account linked
  changelog.txt
  includes/admin/class-wc-rest-stripe-account-controller.php
  includes/class-wc-stripe-account.php
  readme.txt
Labels: pr: ready to merge

#2269 Wrap account summary API in WP_REST_Response
  changelog.txt
  includes/admin/class-wc-rest-stripe-account-controller.php
  includes/class-wc-stripe-account.php
  readme.txt
Labels: pr: needs review

#2280 Fix JS tests on fresh `npm install`s
  client/entrypoints/payment-request-settings/__tests__/payment-request-button-preview.test.js
  client/settings/customization-options-notice/__tests__/customization-options-notice.test.js
  package-lock.json
Labels: pr: in progress

#2287 Fix Translations not loaded in admin (UPE / JSON)
  includes/admin/class-wc-stripe-old-settings-upe-toggle-controller.php
  includes/admin/class-wc-stripe-payment-gateways-controller.php
  includes/admin/class-wc-stripe-payment-requests-controller.php
  includes/admin/class-wc-stripe-settings-controller.php
Labels: pr: needs review

#2286 Adjust modal z-index's overlay to be able to see messages
  changelog.txt
  client/settings/payment-settings/style.scss
  readme.txt
Labels: pr: needs review

#2288 Fix npm run xdebug:stop
  package.json
Labels: pr: needs review

#2253 Fix duplicate `wc_stripe_params` enqueued variable
  assets/js/stripe-payment-request.js
  changelog.txt
  includes/payment-methods/class-wc-stripe-payment-request.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  readme.txt
Labels: pr: needs review

#2293 Tweak description name when updating payment intents inside pay order page
  includes/class-wc-stripe-intent-controller.php
Labels: pr: ready to merge

#2291 Use the default UPE title when custom payment method name is empty
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review

#2299 Update tested up to headers
  readme.txt
  woocommerce-gateway-stripe.php
Labels: pr: needs review

#2300 Update changelog.txt and readme.txt for v6.2.0
  changelog.txt
  readme.txt
Labels: pr: needs review
