Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2024-09, with the labels that each got.

#3415 Add title, description and gatewayId for express payment methods
  client/blocks/payment-request/index.js
Labels: type: enhancement

#3164 Integrate express payments buttonAttributes API from the Checkout Block
  client/blocks/payment-request/payment-request-express.js
  client/entrypoints/payment-request-settings/payment-request-settings-section.js
  package-lock.json
  package.json
Labels: component: blocks, category: compatibility

#3373 Fix Cash App Payments in live mode
  changelog.txt
  includes/class-wc-stripe-intent-controller.php
  readme.txt
Labels: pr: needs review

#3474 Display the WeChat Pay icon on the legacy checkout
  changelog.txt
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  readme.txt
Labels: pr: ready to merge

#3451 Subscription renewal orders are missing the statement descriptor in Stripe
  changelog.txt
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  readme.txt
Labels: pr: ready to merge

#3444 Move charge related code to separate try-catch to prevent renewal failure
  changelog.txt
  includes/compat/trait-wc-stripe-subscriptions.php
  readme.txt
Labels: pr: ready to merge

#3473 Move Stripe Link button to JS for shortcode checkout
  changelog.txt
  client/blocks/upe/hooks.js
  client/classic/upe/deferred-intent.js
  client/stripe-link/index.js
  readme.txt
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge
