Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2024-08, with the labels that each got.

#3336 Fix E2E setup error
  package-lock.json
  tests/e2e/bin/setup.sh
  tests/e2e/tests/_legacy-experience/checkout/sca-card.spec.js
  tests/e2e/tests/checkout/blocks/sca-card.spec.js
  tests/e2e/tests/checkout/shortcode/sca-card.spec.js
Labels: type: technical debt

#3260 Address QIT Security test errors
  .github/workflows/generate-zip.yml
  .github/workflows/qit.yml
  changelog.txt
  includes/admin/class-wc-stripe-settings-controller.php
  includes/class-wc-gateway-stripe.php
  includes/payment-methods/class-wc-gateway-stripe-alipay.php
  includes/payment-methods/class-wc-gateway-stripe-bancontact.php
  includes/payment-methods/class-wc-gateway-stripe-boleto.php
  includes/payment-methods/class-wc-gateway-stripe-eps.php
  includes/payment-methods/class-wc-gateway-stripe-giropay.php
  includes/payment-methods/class-wc-gateway-stripe-ideal.php
  includes/payment-methods/class-wc-gateway-stripe-multibanco.php
  includes/payment-methods/class-wc-gateway-stripe-oxxo.php
  includes/payment-methods/class-wc-gateway-stripe-p24.php
  includes/payment-methods/class-wc-gateway-stripe-sepa.php
  includes/payment-methods/class-wc-gateway-stripe-sofort.php
  readme.txt
  templates/emails/failed-preorder-authentication.php
Labels: needs: qit security test

#3268 Address QIT PHPStan test errors
  changelog.txt
  includes/abstracts/abstract-wc-stripe-connect-rest-controller.php
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/class-wc-stripe-admin-notices.php
  includes/admin/class-wc-stripe-privacy.php
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-blocks-support.php
  includes/class-wc-stripe-helper.php
  includes/class-wc-stripe-payment-tokens.php
  includes/compat/class-wc-stripe-email-failed-authentication-retry.php
  includes/compat/class-wc-stripe-email-failed-renewal-authentication.php
  includes/compat/trait-wc-stripe-pre-orders.php
  includes/compat/trait-wc-stripe-subscriptions-utilities.php
  includes/compat/trait-wc-stripe-subscriptions.php
  includes/payment-methods/class-wc-gateway-stripe-sepa.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
  readme.txt
  templates/emails/failed-renewal-authentication-requested.php
  templates/emails/plain/failed-renewal-authentication-requested.php
Labels: needs: qit phpstan test
