Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2024-05, with the labels that each got.

#2996 Add more detailed error details to a subscription renewal failure
  changelog.txt
  includes/compat/trait-wc-stripe-subscriptions.php
  readme.txt
Labels: pr: needs review

#3108 Restrict Affirm and Klarna to domestic and cross EEA border transactions
  includes/class-wc-stripe-helper.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-klarna.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
Labels: pr: needs review

#3050 Promotional Stripe banner in settings
  changelog.txt
  client/settings/notices/legacy-experience-transition/__tests__/legacy-experience-transition.test.js
  client/settings/notices/legacy-experience-transition/index.js
  client/settings/payment-settings/__tests__/promotional-banner-section.test.js
  client/settings/payment-settings/banner-illustration.svg
  client/settings/payment-settings/index.js
  client/settings/payment-settings/promotional-banner-section.js
  readme.txt
Labels: status: blocked

#3144 Fix deprecated messages on PHP 8.2 from using FILTER_SANITIZE_STRING
  changelog.txt
  includes/class-wc-stripe-customer.php
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: pr: needs review

#3068 Fixes invalid recurring shipping method error when purchasing multiple subscriptions with Apple Pay or Google Pay
  changelog.txt
  includes/payment-methods/class-wc-stripe-payment-request.php
  readme.txt
Labels: pr: needs review

#3166 Declare compatibility with the Cart and Checkout blocks
  changelog.txt
  readme.txt
  woocommerce-gateway-stripe.php
Labels: pr: needs review, component: blocks, category: compatibility
