Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2024-03, with the labels that each got.

#2987 Fix issue with saving plugin settings when existent bank descriptor is no longer valid
  changelog.txt
  includes/admin/class-wc-rest-stripe-settings-controller.php
  readme.txt
  tests/phpunit/admin/test-class-wc-rest-stripe-settings-controller.php
Labels: pr: ready to merge

#2985 Include Stripe API version in logs
  changelog.txt
  includes/class-wc-stripe-api.php
  includes/class-wc-stripe-logger.php
  readme.txt
Labels: pr: ready to merge

#2989 Updating StripeJS library to support card brand choice
  changelog.txt
  package-lock.json
  package.json
  readme.txt
Labels: pr: needs review

#2991 Fix order amount for currencies with 3 decimal places
  changelog.txt
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/class-wc-stripe-helper.php
  readme.txt
  tests/phpunit/test-wc-stripe-helper.php
Labels: pr: needs review

#3012 Add Requires plugins header
  changelog.txt
  woocommerce-gateway-stripe.php
Labels: priority: low, type: technical debt

#2423 Hide refund button for non-captured orders
  changelog.txt
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/admin/class-wc-stripe-settings-controller.php
  readme.txt
  tests/phpunit/admin/test-class-wc-stripe-settings-controller.php
  woocommerce-gateway-stripe.php
Labels: pr: needs review
