Repository woocommerce/woocommerce-gateway-stripe, pull requests merged in 2024-02, with the labels that each got.

#2853 Move Alipay and Multibanco inside Stripe settings when UPE is disabled
  client/payment-method-icons/alipay/icon.svg
  client/payment-method-icons/alipay/index.js
  client/payment-method-icons/multibanco/icon.svg
  client/payment-method-icons/multibanco/index.js
  client/payment-methods-map.js
  includes/class-wc-gateway-stripe.php
  includes/class-wc-stripe-helper.php
  includes/payment-methods/class-wc-gateway-stripe-multibanco.php
  tests/phpunit/admin/test-class-wc-rest-stripe-payment-gateway-controller.php
  tests/phpunit/test-wc-stripe-helper.php
  woocommerce-gateway-stripe.php
Labels: pr: ready to merge

#2869 Removing expandable menu for payment methods when UPE is disabled
  changelog.txt
  client/settings/general-settings-section/__tests__/general-settings-section.test.js
  client/settings/general-settings-section/section-heading.js
  readme.txt
Labels: pr: ready to merge

#2877 Fixing redirection on plugin enablement
  changelog.txt
  includes/class-wc-gateway-stripe.php
  readme.txt
  tests/phpunit/test-wc-stripe-payment-gateway.php
Labels: pr: needs review

#2845 Reusing payment intents when possible
  includes/class-wc-stripe-intent-controller.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  tests/phpunit/test-class-wc-stripe-upe-payment-gateway.php
  tests/phpunit/test-wc-stripe-intent-controller.php
Labels: pr: needs review

#2883 Add APM support for Subscriptions and tokens with split UPE with deferred intent
  client/blocks/upe/index.js
  client/blocks/upe/upe-deferred-intent-creation/payment-elements.js
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/class-wc-stripe-blocks-support.php
  includes/class-wc-stripe-helper.php
  includes/class-wc-stripe-intent-controller.php
  includes/class-wc-stripe-payment-tokens.php
  includes/compat/trait-wc-stripe-subscriptions.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-bancontact.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-boleto.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-cc.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-ideal.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-oxxo.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-sepa.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-sofort.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
Labels: pr: needs review

#2903 Fix E2E tests in latest WC
  tests/e2e/config/local.env.example
  tests/e2e/test-data/cart-shortcode-content.html
  tests/e2e/test-data/checkout-shortcode-content.html
  tests/e2e/tests/checkout/card-failures.spec.js
  tests/e2e/tests/checkout/sca-card.spec.js
  tests/e2e/tests/subscriptions/subscription-renewal.spec.js
  tests/e2e/tests/woocommerce-blocks/sca-card.spec.js
  tests/e2e/utils/payments.js
  tests/e2e/utils/playwright-setup.js
Labels: type: technical debt

#2918 Deferred intent UPE - Fix errors when attempting to add payment methods via My Account > Payment methods
  client/api/index.js
  client/classic/upe/payment-processing.js
  includes/class-wc-stripe-intent-controller.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-sepa.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
Labels: pr: needs review

#2917 [Split PE] Make sure cards are saved when purchasing a regular product with an APM (ideal, SEPA, bancontact)
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review

#2911 Fix pre-orders status when UPE is enabled (with a new payment method)
  changelog.txt
  includes/abstracts/abstract-wc-stripe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  readme.txt
Labels: pr: needs review

#2927 Deferred intent - Display a detailed error message to customers on card declines
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: ready to merge

#2924 Split upe w' deferred intent - don't display APMs on classic checkout while auth and capture is enabled
  includes/payment-methods/class-wc-stripe-upe-payment-method-link.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
  tests/phpunit/test-class-wc-stripe-upe-payment-method.php
Labels: pr: ready to merge

#2915 Update our `filter_gateway_title()` function to work in HPOS but also fix it from overriding the stripe payment method title
  includes/payment-methods/class-wc-stripe-payment-request.php
Labels: pr: needs review

#2930 [Split PE] Don't render the Stripe Link payment method option on classic checkouts
  includes/payment-methods/class-wc-stripe-upe-payment-method-link.php
Labels: pr: ready to merge

#2929 [Split PE] Create the token on returning to the store with Bancontact, iDEAL, Sofort
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: ready to merge

#2951 Split PE - Set the order's payment method ID to the processing payment method
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review

#2952 [Split PE] Fix errors on checkout caused by attempting to reuse intents that require action or require manual confirmation
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  tests/phpunit/test-class-wc-stripe-upe-payment-gateway.php
Labels: pr: needs review

#2948 [Split PE] Fix purchasing with Alipay with our deferred intent changes
  client/stripe-utils/constants.js
  includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
  includes/payment-methods/class-wc-stripe-upe-payment-method-alipay.php
  includes/payment-methods/class-wc-stripe-upe-payment-method.php
  tests/phpunit/test-class-wc-stripe-upe-payment-method.php
Labels: pr: needs review

#2960 Show banner when capabilities list is empty
  client/settings/account-activation-notice/__tests__/account-activation-notice.test.js
  client/settings/account-activation-notice/index.js
Labels: pr: ready to merge
